---
# This is an example playbook to execute Ansible tests.
- name: Verify
  hosts: all
  gather_facts: false

  tasks:
    # test package is installed
    - name: populate package facts
      package_facts:
        manager: "auto"

    - name: test docker-ce is installed
      assert:
        that: "'docker-ce' in ansible_facts.packages"

    # test service is running
    - name: populate service facts
      service_facts:

    - name: test docker service exists and is running
      assert:
        that:
          - "ansible_facts.services['docker'] is defined"
          - "ansible_facts.services['docker'].state == 'running'"
