package com.iscweb.common.events;

import com.iscweb.common.annotations.EventPath;
import com.iscweb.common.model.EntityType;
import com.iscweb.common.model.event.IExternalEntityEvent;
import com.iscweb.common.model.event.ITypedPayload;
import com.iscweb.common.util.EventUtils;
import lombok.Getter;
import lombok.Setter;

/**
 * Base class for all not-processed yet device events.
 *
 * Important: It should be guaranteed that EntityEvent has correct device identification and device type carried on.
 * Using such id and type we can resolve and map internal ISC device record to the event.
 * Because the device event usually generated by integration sub-system the provided device id will refer to the device
 * id in that subsystem and not ISC internal device id. I.e. internal ISC device id can be just not available in the context
 * when EntityEvent generated.
 *
 * @param <T>
 */
@EventPath(path = BaseExternalEntityRawEvent.PATH, root = true)
public abstract class BaseExternalEntityRawEvent<T extends ITypedPayload> extends BaseEvent<T> implements IExternalEntityEvent<T> {
    public static final String PATH = "event.raw.device";

    @Getter
    @Setter
    private String externalEntityId;

    @Getter
    @Setter
    private EntityType entityType;

    @Override
    public String getEventPath() {
        return EventUtils.generatePath(BaseExternalEntityRawEvent.PATH);
    }
}
