version: '3.3'

networks:
  default:
    name: isc-network

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  isc-prometheus:
    image: prom/prometheus:v2.32.1
    container_name: "isc-prometheus"
    restart: always
    volumes:
      - ./prometheus:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--web.listen-address=0.0.0.0:9001'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9001:9001
    # links:
    #   - isc-cadvisor:cadvisor
    #   - isc-alertmanager:alertmanager
    depends_on:
      - isc-cadvisor
      - isc-alertmanager

  isc-node-exporter:
    image: prom/node-exporter
    container_name: "isc-node-exporter"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - '^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'
    ports:
      - 9100:9100
    restart: always
    deploy:
      mode: global

  isc-alertmanager:
    image: prom/alertmanager
    container_name: "isc-alertmanager"
    restart: always
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  isc-cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: "isc-cadvisor"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    restart: always
    deploy:
      mode: global

  isc-grafana:
    image: grafana/grafana:8.3.3
    container_name: "isc-grafana"
    user: '472'
    restart: always
    environment:
      GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-simple-json-datasource'
    volumes:
      - type: bind
        source: "./grafana/provisioning/"
        target: /etc/grafana/provisioning/
      - type: bind
        source: "/opt/data/data/isc-grafana"
        target: /var/lib/grafana
    env_file:
      - ./grafana/config.monitoring
    ports:
      - 9000:3000
    depends_on:
      - isc-prometheus
