/**
 * Authorization Roles
 */
const authRoles = {
    Guest: ['ROLE_SYSTEM_ADMINISTRATOR', 'ROLE_DISTRICT_ADMINISTRATOR', 'ROLE_ANALYST', 'ROLE_GUARD', 'ROLE_GUEST'],
    Guard: ['ROLE_SYSTEM_ADMINISTRATOR', 'ROLE_DISTRICT_ADMINISTRATOR', 'ROLE_ANALYST', 'ROLE_GUARD'],
    Analyst: ['ROLE_ANALYST'],
    Administrator: ['ROLE_SYSTEM_ADMINISTRATOR', 'ROLE_DISTRICT_ADMINISTRATOR'],
    Dashboards: ['ROLE_GUARD', 'ROLE_ANALYST', 'ROLE_SYSTEM_ADMINISTRATOR', 'ROLE_DISTRICT_ADMINISTRATOR'],
    SystemAdministrator: ['ROLE_SYSTEM_ADMINISTRATOR'],
    AnyAuthenticated: ['ROLE_SYSTEM_ADMINISTRATOR', 'ROLE_DISTRICT_ADMINISTRATOR', 'ROLE_ANALYST', 'ROLE_GUARD'],
    OnlyGuest: [],
};

export default authRoles;
