
package com.mip.config;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2021-11-02T20:25:02.418-07:00
 * Generated source version: 3.3.6
 *
 */
public final class IConfigurationService_WSHttpBindingIConfigurationService_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "ConfigurationApiService");

    private IConfigurationService_WSHttpBindingIConfigurationService_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ConfigurationApiService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ConfigurationApiService ss = new ConfigurationApiService(wsdlURL, SERVICE_NAME);
        IConfigurationService port = ss.getWSHttpBindingIConfigurationService();

        {
        System.out.println("Invoking setItem...");
        com.mip.config.ConfigurationItem _setItem_item = null;
        try {
            com.mip.config.ValidateResult _setItem__return = port.setItem(_setItem_item);
            System.out.println("setItem.result=" + _setItem__return);

        } catch (IConfigurationServiceSetItemArgumentNullExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_SetItem_ArgumentNullExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceSetItemArgumentExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_SetItem_ArgumentExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceSetItemServerExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_SetItem_ServerExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceSetItemPathNotFoundExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_SetItem_PathNotFoundExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceSetItemNotSupportedExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_SetItem_NotSupportedExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceSetItemUnauthorizedAccessFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_SetItem_UnauthorizedAccessFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceSetItemLicenseExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_SetItem_LicenseExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking validateItem...");
        com.mip.config.ConfigurationItem _validateItem_item = null;
        try {
            com.mip.config.ValidateResult _validateItem__return = port.validateItem(_validateItem_item);
            System.out.println("validateItem.result=" + _validateItem__return);

        } catch (IConfigurationServiceValidateItemArgumentNullExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_ValidateItem_ArgumentNullExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceValidateItemArgumentExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_ValidateItem_ArgumentExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceValidateItemServerExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_ValidateItem_ServerExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceValidateItemPathNotFoundExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_ValidateItem_PathNotFoundExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceValidateItemNotSupportedExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_ValidateItem_NotSupportedExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceValidateItemUnauthorizedAccessFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_ValidateItem_UnauthorizedAccessFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceValidateItemLicenseExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_ValidateItem_LicenseExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getItem...");
        java.lang.String _getItem_path = "";
        try {
            com.mip.config.ConfigurationItem _getItem__return = port.getItem(_getItem_path);
            System.out.println("getItem.result=" + _getItem__return);

        } catch (IConfigurationServiceGetItemArgumentNullExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetItem_ArgumentNullExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetItemArgumentExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetItem_ArgumentExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetItemServerExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetItem_ServerExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetItemPathNotFoundExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetItem_PathNotFoundExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetItemNotSupportedExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetItem_NotSupportedExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetItemUnauthorizedAccessFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetItem_UnauthorizedAccessFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetItemLicenseExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetItem_LicenseExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getChildItems...");
        java.lang.String _getChildItems_path = "";
        try {
            com.mip.config.ArrayOfConfigurationItem _getChildItems__return = port.getChildItems(_getChildItems_path);
            System.out.println("getChildItems.result=" + _getChildItems__return);

        } catch (IConfigurationServiceGetChildItemsArgumentNullExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetChildItems_ArgumentNullExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetChildItemsArgumentExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetChildItems_ArgumentExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetChildItemsServerExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetChildItems_ServerExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetChildItemsPathNotFoundExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetChildItems_PathNotFoundExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetChildItemsNotSupportedExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetChildItems_NotSupportedExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetChildItemsUnauthorizedAccessFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetChildItems_UnauthorizedAccessFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetChildItemsLicenseExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetChildItems_LicenseExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking hasChildItems...");
        java.lang.String _hasChildItems_path = "";
        try {
            java.lang.Boolean _hasChildItems__return = port.hasChildItems(_hasChildItems_path);
            System.out.println("hasChildItems.result=" + _hasChildItems__return);

        } catch (IConfigurationServiceHasChildItemsArgumentNullExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_HasChildItems_ArgumentNullExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceHasChildItemsArgumentExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_HasChildItems_ArgumentExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceHasChildItemsServerExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_HasChildItems_ServerExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceHasChildItemsPathNotFoundExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_HasChildItems_PathNotFoundExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceHasChildItemsNotSupportedExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_HasChildItems_NotSupportedExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceHasChildItemsUnauthorizedAccessFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_HasChildItems_UnauthorizedAccessFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceHasChildItemsLicenseExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_HasChildItems_LicenseExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getChildItemsHierarchy...");
        java.lang.String _getChildItemsHierarchy_path = "";
        com.mip.config.ArrayOfstring _getChildItemsHierarchy_itemTypes = null;
        com.mip.config.ArrayOfItemFilter _getChildItemsHierarchy_itemFilters = null;
        try {
            com.mip.config.ArrayOfConfigurationItem _getChildItemsHierarchy__return = port.getChildItemsHierarchy(_getChildItemsHierarchy_path, _getChildItemsHierarchy_itemTypes, _getChildItemsHierarchy_itemFilters);
            System.out.println("getChildItemsHierarchy.result=" + _getChildItemsHierarchy__return);

        } catch (IConfigurationServiceGetChildItemsHierarchyArgumentNullExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetChildItemsHierarchy_ArgumentNullExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetChildItemsHierarchyArgumentExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetChildItemsHierarchy_ArgumentExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetChildItemsHierarchyServerExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetChildItemsHierarchy_ServerExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetChildItemsHierarchyPathNotFoundExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetChildItemsHierarchy_PathNotFoundExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetChildItemsHierarchyNotSupportedExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetChildItemsHierarchy_NotSupportedExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetChildItemsHierarchyUnauthorizedAccessFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetChildItemsHierarchy_UnauthorizedAccessFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetChildItemsHierarchyLicenseExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetChildItemsHierarchy_LicenseExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getItems...");
        java.lang.String _getItems_itemType = "";
        try {
            com.mip.config.ArrayOfConfigurationItem _getItems__return = port.getItems(_getItems_itemType);
            System.out.println("getItems.result=" + _getItems__return);

        } catch (IConfigurationServiceGetItemsArgumentNullExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetItems_ArgumentNullExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetItemsArgumentExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetItems_ArgumentExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetItemsServerExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetItems_ServerExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetItemsPathNotFoundExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetItems_PathNotFoundExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetItemsNotSupportedExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetItems_NotSupportedExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetItemsUnauthorizedAccessFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetItems_UnauthorizedAccessFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetItemsLicenseExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetItems_LicenseExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getTranslations...");
        java.lang.String _getTranslations_languageId = "";
        try {
            com.mip.config.ArrayOfKeyValueOfstringstring _getTranslations__return = port.getTranslations(_getTranslations_languageId);
            System.out.println("getTranslations.result=" + _getTranslations__return);

        } catch (IConfigurationServiceGetTranslationsArgumentNullExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetTranslations_ArgumentNullExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetTranslationsArgumentExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetTranslations_ArgumentExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetTranslationsServerExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetTranslations_ServerExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetTranslationsPathNotFoundExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetTranslations_PathNotFoundExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetTranslationsNotSupportedExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetTranslations_NotSupportedExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetTranslationsUnauthorizedAccessFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetTranslations_UnauthorizedAccessFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetTranslationsLicenseExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetTranslations_LicenseExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking constructItem...");
        java.lang.String _constructItem_itemType = "";
        com.mip.config.ArrayOfProperty _constructItem_properties = null;
        try {
            com.mip.config.ConfigurationItem _constructItem__return = port.constructItem(_constructItem_itemType, _constructItem_properties);
            System.out.println("constructItem.result=" + _constructItem__return);

        } catch (IConfigurationServiceConstructItemArgumentNullExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_ConstructItem_ArgumentNullExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceConstructItemArgumentExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_ConstructItem_ArgumentExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceConstructItemServerExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_ConstructItem_ServerExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceConstructItemPathNotFoundExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_ConstructItem_PathNotFoundExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceConstructItemNotSupportedExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_ConstructItem_NotSupportedExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceConstructItemUnauthorizedAccessFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_ConstructItem_UnauthorizedAccessFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceConstructItemLicenseExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_ConstructItem_LicenseExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getDependantItems...");
        java.lang.String _getDependantItems_path = "";
        try {
            com.mip.config.ArrayOfConfigurationItem _getDependantItems__return = port.getDependantItems(_getDependantItems_path);
            System.out.println("getDependantItems.result=" + _getDependantItems__return);

        } catch (IConfigurationServiceGetDependantItemsArgumentNullExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetDependantItems_ArgumentNullExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetDependantItemsArgumentExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetDependantItems_ArgumentExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetDependantItemsServerExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetDependantItems_ServerExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetDependantItemsPathNotFoundExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetDependantItems_PathNotFoundExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetDependantItemsNotSupportedExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetDependantItems_NotSupportedExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetDependantItemsUnauthorizedAccessFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetDependantItems_UnauthorizedAccessFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetDependantItemsLicenseExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetDependantItems_LicenseExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking deleteItem...");
        java.lang.String _deleteItem_path = "";
        try {
            port.deleteItem(_deleteItem_path);

        } catch (IConfigurationServiceDeleteItemArgumentNullExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_DeleteItem_ArgumentNullExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceDeleteItemArgumentExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_DeleteItem_ArgumentExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceDeleteItemServerExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_DeleteItem_ServerExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceDeleteItemPathNotFoundExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_DeleteItem_PathNotFoundExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceDeleteItemNotSupportedExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_DeleteItem_NotSupportedExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceDeleteItemUnauthorizedAccessFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_DeleteItem_UnauthorizedAccessFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceDeleteItemLicenseExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_DeleteItem_LicenseExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getMethodInfo...");
        java.lang.String _getMethodInfo_methodId = "";
        try {
            com.mip.config.MethodInfo _getMethodInfo__return = port.getMethodInfo(_getMethodInfo_methodId);
            System.out.println("getMethodInfo.result=" + _getMethodInfo__return);

        } catch (IConfigurationServiceGetMethodInfoArgumentNullExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetMethodInfo_ArgumentNullExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetMethodInfoArgumentExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetMethodInfo_ArgumentExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetMethodInfoServerExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetMethodInfo_ServerExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetMethodInfoPathNotFoundExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetMethodInfo_PathNotFoundExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetMethodInfoNotSupportedExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetMethodInfo_NotSupportedExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetMethodInfoUnauthorizedAccessFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetMethodInfo_UnauthorizedAccessFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetMethodInfoLicenseExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetMethodInfo_LicenseExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking invokeMethod...");
        com.mip.config.ConfigurationItem _invokeMethod_item = null;
        java.lang.String _invokeMethod_method = "";
        try {
            com.mip.config.ConfigurationItem _invokeMethod__return = port.invokeMethod(_invokeMethod_item, _invokeMethod_method);
            System.out.println("invokeMethod.result=" + _invokeMethod__return);

        } catch (IConfigurationServiceInvokeMethodArgumentNullExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_InvokeMethod_ArgumentNullExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceInvokeMethodArgumentExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_InvokeMethod_ArgumentExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceInvokeMethodServerExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_InvokeMethod_ServerExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceInvokeMethodPathNotFoundExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_InvokeMethod_PathNotFoundExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceInvokeMethodNotSupportedExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_InvokeMethod_NotSupportedExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceInvokeMethodUnauthorizedAccessFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_InvokeMethod_UnauthorizedAccessFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceInvokeMethodLicenseExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_InvokeMethod_LicenseExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking constructChildItem...");
        java.lang.String _constructChildItem_itemType = "";
        java.lang.String _constructChildItem_parentPath = "";
        try {
            com.mip.config.ConfigurationItem _constructChildItem__return = port.constructChildItem(_constructChildItem_itemType, _constructChildItem_parentPath);
            System.out.println("constructChildItem.result=" + _constructChildItem__return);

        } catch (IConfigurationServiceConstructChildItemArgumentNullExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_ConstructChildItem_ArgumentNullExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceConstructChildItemArgumentExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_ConstructChildItem_ArgumentExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceConstructChildItemServerExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_ConstructChildItem_ServerExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceConstructChildItemPathNotFoundExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_ConstructChildItem_PathNotFoundExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceConstructChildItemNotSupportedExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_ConstructChildItem_NotSupportedExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceConstructChildItemUnauthorizedAccessFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_ConstructChildItem_UnauthorizedAccessFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceConstructChildItemLicenseExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_ConstructChildItem_LicenseExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getMethodInfos...");
        try {
            com.mip.config.ArrayOfMethodInfo _getMethodInfos__return = port.getMethodInfos();
            System.out.println("getMethodInfos.result=" + _getMethodInfos__return);

        } catch (IConfigurationServiceGetMethodInfosArgumentNullExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetMethodInfos_ArgumentNullExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetMethodInfosArgumentExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetMethodInfos_ArgumentExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetMethodInfosServerExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetMethodInfos_ServerExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetMethodInfosPathNotFoundExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetMethodInfos_PathNotFoundExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetMethodInfosNotSupportedExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetMethodInfos_NotSupportedExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetMethodInfosUnauthorizedAccessFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetMethodInfos_UnauthorizedAccessFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceGetMethodInfosLicenseExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_GetMethodInfos_LicenseExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking queryItems...");
        com.mip.config.ItemFilter _queryItems_itemFilter = null;
        java.lang.Integer _queryItems_maxResult = null;
        try {
            com.mip.config.ArrayOfConfigurationItem _queryItems__return = port.queryItems(_queryItems_itemFilter, _queryItems_maxResult);
            System.out.println("queryItems.result=" + _queryItems__return);

        } catch (IConfigurationServiceQueryItemsArgumentNullExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_QueryItems_ArgumentNullExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceQueryItemsArgumentExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_QueryItems_ArgumentExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceQueryItemsServerExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_QueryItems_ServerExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceQueryItemsPathNotFoundExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_QueryItems_PathNotFoundExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceQueryItemsNotSupportedExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_QueryItems_NotSupportedExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceQueryItemsUnauthorizedAccessFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_QueryItems_UnauthorizedAccessFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (IConfigurationServiceQueryItemsLicenseExceptionFaultFaultFaultMessage e) {
            System.out.println("Expected exception: IConfigurationService_QueryItems_LicenseExceptionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }

            }

        System.exit(0);
    }

}
