package com.mip.command;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2021-11-02T20:25:00.408-07:00
 * Generated source version: 3.3.6
 *
 */
@WebService(targetNamespace = "http://video.net/2/XProtectCSServerCommand", name = "IServerCommandService")
@XmlSeeAlso({ObjectFactory.class})
public interface IServerCommandService {

    @WebMethod(operationName = "SetCustomSettingDataGlobal", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/SetCustomSettingDataGlobal")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/SetCustomSettingDataGlobal", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/SetCustomSettingDataGlobalResponse")
    @RequestWrapper(localName = "SetCustomSettingDataGlobal", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.SetCustomSettingDataGlobal")
    @ResponseWrapper(localName = "SetCustomSettingDataGlobalResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.SetCustomSettingDataGlobalResponse")
    @WebResult(name = "SetCustomSettingDataGlobalResult", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public com.mip.command.SetCustomSettingResultType setCustomSettingDataGlobal(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "customSettingId", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String customSettingId,
        @WebParam(name = "customSettingData", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        com.mip.command.CustomSettingInternalData customSettingData,
        @WebParam(name = "forceOverride", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.Boolean forceOverride
    );

    @WebMethod(operationName = "GetClientProfile3", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetClientProfile3")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetClientProfile3", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetClientProfile3Response")
    @RequestWrapper(localName = "GetClientProfile3", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.GetClientProfile3")
    @ResponseWrapper(localName = "GetClientProfile3Response", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.GetClientProfile3Response")
    @WebResult(name = "GetClientProfile3Result", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public com.mip.command.ClientProfile getClientProfile3(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "withSetting", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.Boolean withSetting
    );

    @WebMethod(operationName = "SetCustomSettingDataUser", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/SetCustomSettingDataUser")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/SetCustomSettingDataUser", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/SetCustomSettingDataUserResponse")
    @RequestWrapper(localName = "SetCustomSettingDataUser", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.SetCustomSettingDataUser")
    @ResponseWrapper(localName = "SetCustomSettingDataUserResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.SetCustomSettingDataUserResponse")
    @WebResult(name = "SetCustomSettingDataUserResult", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public com.mip.command.SetCustomSettingResultType setCustomSettingDataUser(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "customSettingId", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String customSettingId,
        @WebParam(name = "customSettingData", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        com.mip.command.CustomSettingInternalData customSettingData,
        @WebParam(name = "forceOverride", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.Boolean forceOverride
    );

    @WebMethod(operationName = "GetClientProfile2", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetClientProfile2")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetClientProfile2", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetClientProfile2Response")
    @RequestWrapper(localName = "GetClientProfile2", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.GetClientProfile2")
    @ResponseWrapper(localName = "GetClientProfile2Response", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.GetClientProfile2Response")
    @WebResult(name = "GetClientProfile2Result", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public com.mip.command.ClientProfile getClientProfile2(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "withSetting", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.Boolean withSetting
    );

    @WebMethod(operationName = "GetServerVersion", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetServerVersion")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetServerVersion", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetServerVersionResponse")
    @RequestWrapper(localName = "GetServerVersion", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.GetServerVersion")
    @ResponseWrapper(localName = "GetServerVersionResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.GetServerVersionResponse")
    @WebResult(name = "GetServerVersionResult", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public java.lang.String getServerVersion()
;

    @WebMethod(operationName = "GetViewGroupData", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetViewGroupData")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetViewGroupData", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetViewGroupDataResponse")
    @RequestWrapper(localName = "GetViewGroupData", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.GetViewGroupData")
    @ResponseWrapper(localName = "GetViewGroupDataResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.GetViewGroupDataResponse")
    @WebResult(name = "GetViewGroupDataResult", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public com.mip.command.ViewGroupInternal getViewGroupData(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "viewGroupId", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String viewGroupId
    );

    @WebMethod(operationName = "MarkedDataCreate", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/MarkedDataCreate")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/MarkedDataCreate", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/MarkedDataCreateResponse")
    @RequestWrapper(localName = "MarkedDataCreate", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.MarkedDataCreate")
    @ResponseWrapper(localName = "MarkedDataCreateResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.MarkedDataCreateResponse")
    @WebResult(name = "MarkedDataCreateResult", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public com.mip.command.MarkedDataResult markedDataCreate(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "markedDataId", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String markedDataId,
        @WebParam(name = "deviceIds", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        com.mip.command.ArrayOfguid deviceIds,
        @WebParam(name = "timeStart", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar timeStart,
        @WebParam(name = "timeTag", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar timeTag,
        @WebParam(name = "timeEnd", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar timeEnd,
        @WebParam(name = "reference", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String reference,
        @WebParam(name = "header", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String header,
        @WebParam(name = "description", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String description,
        @WebParam(name = "markedDataType", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.Integer markedDataType,
        @WebParam(name = "useRetention", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.Boolean useRetention,
        @WebParam(name = "retentionExpire", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar retentionExpire,
        @WebParam(name = "retentionOption", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        com.mip.command.RetentionOption retentionOption
    );

    @WebMethod(operationName = "MatrixMonitorActivateCamera", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/MatrixMonitorActivateCamera")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/MatrixMonitorActivateCamera", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/MatrixMonitorActivateCameraResponse")
    @RequestWrapper(localName = "MatrixMonitorActivateCamera", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.MatrixMonitorActivateCamera")
    @ResponseWrapper(localName = "MatrixMonitorActivateCameraResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.MatrixMonitorActivateCameraResponse")
    public void matrixMonitorActivateCamera(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "matrixMonitorId", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String matrixMonitorId,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String deviceId
    );

    @WebMethod(operationName = "UpdatePresetPosition", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/UpdatePresetPosition")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/UpdatePresetPosition", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/UpdatePresetPositionResponse")
    @RequestWrapper(localName = "UpdatePresetPosition", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.UpdatePresetPosition")
    @ResponseWrapper(localName = "UpdatePresetPositionResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.UpdatePresetPositionResponse")
    public void updatePresetPosition(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "id", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String id,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String deviceId
    );

    @WebMethod(operationName = "GetCustomSettingDataUser", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetCustomSettingDataUser")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetCustomSettingDataUser", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetCustomSettingDataUserResponse")
    @RequestWrapper(localName = "GetCustomSettingDataUser", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.GetCustomSettingDataUser")
    @ResponseWrapper(localName = "GetCustomSettingDataUserResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.GetCustomSettingDataUserResponse")
    @WebResult(name = "GetCustomSettingDataUserResult", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public com.mip.command.CustomSettingInternal getCustomSettingDataUser(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "customSettingId", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String customSettingId
    );

    @WebMethod(operationName = "GetVersion", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetVersion")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetVersion", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetVersionResponse")
    @RequestWrapper(localName = "GetVersion", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.GetVersion")
    @ResponseWrapper(localName = "GetVersionResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.GetVersionResponse")
    @WebResult(name = "GetVersionResult", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public java.lang.Integer getVersion()
;

    @WebMethod(operationName = "Logout", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/Logout")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/Logout", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/LogoutResponse")
    @RequestWrapper(localName = "Logout", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.Logout")
    @ResponseWrapper(localName = "LogoutResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.LogoutResponse")
    public void logout(

        @WebParam(name = "instanceId", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String instanceId,
        @WebParam(name = "currentToken", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String currentToken
    );

    @WebMethod(operationName = "MarkedDataSearch", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/MarkedDataSearch")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/MarkedDataSearch", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/MarkedDataSearchResponse")
    @RequestWrapper(localName = "MarkedDataSearch", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.MarkedDataSearch")
    @ResponseWrapper(localName = "MarkedDataSearchResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.MarkedDataSearchResponse")
    @WebResult(name = "MarkedDataSearchResult", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public com.mip.command.ArrayOfMarkedData markedDataSearch(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "deviceIds", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        com.mip.command.ArrayOfguid deviceIds,
        @WebParam(name = "searchText", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String searchText,
        @WebParam(name = "users", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        com.mip.command.ArrayOfstring users,
        @WebParam(name = "createdFromTime", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar createdFromTime,
        @WebParam(name = "createdToTime", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar createdToTime,
        @WebParam(name = "markedDataFromTime", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar markedDataFromTime,
        @WebParam(name = "markedDataToTime", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar markedDataToTime,
        @WebParam(name = "tagTimeFromTime", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar tagTimeFromTime,
        @WebParam(name = "tagTimeToTime", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar tagTimeToTime,
        @WebParam(name = "retentionExpireFrom", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar retentionExpireFrom,
        @WebParam(name = "retentionExpireTo", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar retentionExpireTo,
        @WebParam(name = "pageIndex", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.Integer pageIndex,
        @WebParam(name = "pageSize", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.Integer pageSize,
        @WebParam(name = "sortOrder", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        com.mip.command.SortOrderOption sortOrder,
        @WebParam(name = "sortAscending", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.Boolean sortAscending
    );

    @WebMethod(operationName = "BookmarkCreate", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/BookmarkCreate")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/BookmarkCreate", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/BookmarkCreateResponse")
    @RequestWrapper(localName = "BookmarkCreate", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.BookmarkCreate")
    @ResponseWrapper(localName = "BookmarkCreateResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.BookmarkCreateResponse")
    @WebResult(name = "BookmarkCreateResult", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public com.mip.command.Bookmark bookmarkCreate(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String deviceId,
        @WebParam(name = "timeBegin", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar timeBegin,
        @WebParam(name = "timeTrigged", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar timeTrigged,
        @WebParam(name = "timeEnd", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar timeEnd,
        @WebParam(name = "reference", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String reference,
        @WebParam(name = "header", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String header,
        @WebParam(name = "description", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String description
    );

    @WebMethod(operationName = "GetVmoServicesList", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetVmoServicesList")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetVmoServicesList", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetVmoServicesListResponse")
    @RequestWrapper(localName = "GetVmoServicesList", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.GetVmoServicesList")
    @ResponseWrapper(localName = "GetVmoServicesListResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.GetVmoServicesListResponse")
    @WebResult(name = "GetVmoServicesListResult", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public com.mip.command.ArrayOfDictionaryEntry getVmoServicesList()
;

    @WebMethod(operationName = "MarkedDataUpdate", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/MarkedDataUpdate")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/MarkedDataUpdate", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/MarkedDataUpdateResponse")
    @RequestWrapper(localName = "MarkedDataUpdate", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.MarkedDataUpdate")
    @ResponseWrapper(localName = "MarkedDataUpdateResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.MarkedDataUpdateResponse")
    @WebResult(name = "MarkedDataUpdateResult", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public com.mip.command.MarkedDataResult markedDataUpdate(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "markedDataId", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String markedDataId,
        @WebParam(name = "deviceIds", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        com.mip.command.ArrayOfguid deviceIds,
        @WebParam(name = "timeStart", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar timeStart,
        @WebParam(name = "timeTag", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar timeTag,
        @WebParam(name = "timeEnd", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar timeEnd,
        @WebParam(name = "reference", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String reference,
        @WebParam(name = "header", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String header,
        @WebParam(name = "description", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String description,
        @WebParam(name = "markedDataType", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.Integer markedDataType,
        @WebParam(name = "useRetention", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.Boolean useRetention,
        @WebParam(name = "retentionExpire", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar retentionExpire,
        @WebParam(name = "retentionOption", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        com.mip.command.RetentionOption retentionOption
    );

    @WebMethod(operationName = "CheckSmartClientVersion", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/CheckSmartClientVersion")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/CheckSmartClientVersion", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/CheckSmartClientVersionResponse")
    @RequestWrapper(localName = "CheckSmartClientVersion", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.CheckSmartClientVersion")
    @ResponseWrapper(localName = "CheckSmartClientVersionResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.CheckSmartClientVersionResponse")
    @WebResult(name = "CheckSmartClientVersionResult", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public com.mip.command.SmartClientVersion checkSmartClientVersion(

        @WebParam(name = "major", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.Integer major,
        @WebParam(name = "minor", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.Integer minor,
        @WebParam(name = "revision", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String revision
    );

    @WebMethod(operationName = "GetConfigurationHardware", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetConfigurationHardware")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetConfigurationHardware", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetConfigurationHardwareResponse")
    @RequestWrapper(localName = "GetConfigurationHardware", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.GetConfigurationHardware")
    @ResponseWrapper(localName = "GetConfigurationHardwareResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.GetConfigurationHardwareResponse")
    @WebResult(name = "GetConfigurationHardwareResult", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public com.mip.command.ArrayOfHardwareInfo getConfigurationHardware(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "hardwareIds", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        com.mip.command.ArrayOfguid hardwareIds
    );

    @WebMethod(operationName = "GetViewGroups", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetViewGroups")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetViewGroups", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetViewGroupsResponse")
    @RequestWrapper(localName = "GetViewGroups", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.GetViewGroups")
    @ResponseWrapper(localName = "GetViewGroupsResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.GetViewGroupsResponse")
    @WebResult(name = "GetViewGroupsResult", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public com.mip.command.ArrayOfViewGroupInfo getViewGroups(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token
    );

    @WebMethod(operationName = "BookmarkGetNewReference", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/BookmarkGetNewReference")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/BookmarkGetNewReference", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/BookmarkGetNewReferenceResponse")
    @RequestWrapper(localName = "BookmarkGetNewReference", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.BookmarkGetNewReference")
    @ResponseWrapper(localName = "BookmarkGetNewReferenceResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.BookmarkGetNewReferenceResponse")
    @WebResult(name = "BookmarkGetNewReferenceResult", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public com.mip.command.BookmarkReference bookmarkGetNewReference(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String deviceId,
        @WebParam(name = "live", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.Boolean live
    );

    @WebMethod(operationName = "GetPresets", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetPresets")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetPresets", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetPresetsResponse")
    @RequestWrapper(localName = "GetPresets", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.GetPresets")
    @ResponseWrapper(localName = "GetPresetsResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.GetPresetsResponse")
    @WebResult(name = "GetPresetsResult", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public com.mip.command.ArrayOfPresetInfo getPresets(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String deviceId
    );

    @WebMethod(operationName = "BookmarkSearchTime", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/BookmarkSearchTime")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/BookmarkSearchTime", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/BookmarkSearchTimeResponse")
    @RequestWrapper(localName = "BookmarkSearchTime", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.BookmarkSearchTime")
    @ResponseWrapper(localName = "BookmarkSearchTimeResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.BookmarkSearchTimeResponse")
    @WebResult(name = "BookmarkSearchTimeResult", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public com.mip.command.ArrayOfBookmark bookmarkSearchTime(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "time", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar time,
        @WebParam(name = "timeLimit", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        com.mip.command.TimeDuration timeLimit,
        @WebParam(name = "countLimit", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.Integer countLimit,
        @WebParam(name = "deviceTypes", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        com.mip.command.ArrayOfMediaDeviceType deviceTypes,
        @WebParam(name = "optDeviceIds", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        com.mip.command.ArrayOfguid optDeviceIds,
        @WebParam(name = "optUsers", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        com.mip.command.ArrayOfstring optUsers,
        @WebParam(name = "optSearchStr", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String optSearchStr
    );

    @WebMethod(operationName = "MarkedDataGetNewReference", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/MarkedDataGetNewReference")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/MarkedDataGetNewReference", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/MarkedDataGetNewReferenceResponse")
    @RequestWrapper(localName = "MarkedDataGetNewReference", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.MarkedDataGetNewReference")
    @ResponseWrapper(localName = "MarkedDataGetNewReferenceResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.MarkedDataGetNewReferenceResponse")
    @WebResult(name = "MarkedDataGetNewReferenceResult", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public com.mip.command.MarkedDataReference markedDataGetNewReference(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        com.mip.command.ArrayOfguid deviceId,
        @WebParam(name = "live", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.Boolean live
    );

    @WebMethod(operationName = "GetClientProfile", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetClientProfile")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetClientProfile", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetClientProfileResponse")
    @RequestWrapper(localName = "GetClientProfile", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.GetClientProfile")
    @ResponseWrapper(localName = "GetClientProfileResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.GetClientProfileResponse")
    @WebResult(name = "GetClientProfileResult", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public com.mip.command.ClientProfile getClientProfile(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "withSetting", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.Boolean withSetting
    );

    @WebMethod(operationName = "BookmarkUpdate", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/BookmarkUpdate")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/BookmarkUpdate", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/BookmarkUpdateResponse")
    @RequestWrapper(localName = "BookmarkUpdate", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.BookmarkUpdate")
    @ResponseWrapper(localName = "BookmarkUpdateResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.BookmarkUpdateResponse")
    @WebResult(name = "BookmarkUpdateResult", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public com.mip.command.Bookmark bookmarkUpdate(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "bookmarkId", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String bookmarkId,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String deviceId,
        @WebParam(name = "timeBegin", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar timeBegin,
        @WebParam(name = "timeTrigged", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar timeTrigged,
        @WebParam(name = "timeEnd", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar timeEnd,
        @WebParam(name = "reference", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String reference,
        @WebParam(name = "header", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String header,
        @WebParam(name = "description", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String description
    );

    @WebMethod(operationName = "GetProductInfo", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetProductInfo")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetProductInfo", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetProductInfoResponse")
    @RequestWrapper(localName = "GetProductInfo", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.GetProductInfo")
    @ResponseWrapper(localName = "GetProductInfoResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.GetProductInfoResponse")
    @WebResult(name = "GetProductInfoResult", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public com.mip.command.ProductInfo getProductInfo()
;

    @WebMethod(operationName = "SetCustomSettingDataUser2", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/SetCustomSettingDataUser2")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/SetCustomSettingDataUser2", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/SetCustomSettingDataUser2Response")
    @RequestWrapper(localName = "SetCustomSettingDataUser2", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.SetCustomSettingDataUser2")
    @ResponseWrapper(localName = "SetCustomSettingDataUser2Response", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.SetCustomSettingDataUser2Response")
    @WebResult(name = "SetCustomSettingDataUser2Result", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public com.mip.command.SetCustomSettingResultType setCustomSettingDataUser2(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "customSettingId", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String customSettingId,
        @WebParam(name = "customSettingData", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        com.mip.command.CustomSettingInternalData customSettingData,
        @WebParam(name = "forceOverride", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.Boolean forceOverride
    );

    @WebMethod(operationName = "CreatePreset", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/CreatePreset")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/CreatePreset", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/CreatePresetResponse")
    @RequestWrapper(localName = "CreatePreset", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.CreatePreset")
    @ResponseWrapper(localName = "CreatePresetResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.CreatePresetResponse")
    @WebResult(name = "CreatePresetResult", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public java.lang.String createPreset(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String deviceId,
        @WebParam(name = "name", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String name
    );

    @WebMethod(operationName = "IsOnline", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/IsOnline")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/IsOnline", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/IsOnlineResponse")
    @RequestWrapper(localName = "IsOnline", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.IsOnline")
    @ResponseWrapper(localName = "IsOnlineResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.IsOnlineResponse")
    @WebResult(name = "IsOnlineResult", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public java.lang.Boolean isOnline()
;

    @WebMethod(operationName = "QueryRecorderInfo", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/QueryRecorderInfo")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/QueryRecorderInfo", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/QueryRecorderInfoResponse")
    @RequestWrapper(localName = "QueryRecorderInfo", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.QueryRecorderInfo")
    @ResponseWrapper(localName = "QueryRecorderInfoResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.QueryRecorderInfoResponse")
    @WebResult(name = "QueryRecorderInfoResult", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public com.mip.command.RecorderInfo queryRecorderInfo(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "recorderId", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String recorderId
    );

    @WebMethod(operationName = "GetCustomSettingDataGlobal", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetCustomSettingDataGlobal")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetCustomSettingDataGlobal", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetCustomSettingDataGlobalResponse")
    @RequestWrapper(localName = "GetCustomSettingDataGlobal", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.GetCustomSettingDataGlobal")
    @ResponseWrapper(localName = "GetCustomSettingDataGlobalResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.GetCustomSettingDataGlobalResponse")
    @WebResult(name = "GetCustomSettingDataGlobalResult", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public com.mip.command.CustomSettingInternal getCustomSettingDataGlobal(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "customSettingId", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String customSettingId
    );

    @WebMethod(operationName = "GetConfigurationRecorders", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetConfigurationRecorders")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetConfigurationRecorders", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetConfigurationRecordersResponse")
    @RequestWrapper(localName = "GetConfigurationRecorders", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.GetConfigurationRecorders")
    @ResponseWrapper(localName = "GetConfigurationRecordersResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.GetConfigurationRecordersResponse")
    @WebResult(name = "GetConfigurationRecordersResult", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public com.mip.command.ArrayOfRecorderInfo getConfigurationRecorders(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "recorderIds", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        com.mip.command.ArrayOfguid recorderIds
    );

    @WebMethod(operationName = "GetSystemLicenseInfo", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetSystemLicenseInfo")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetSystemLicenseInfo", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetSystemLicenseInfoResponse")
    @RequestWrapper(localName = "GetSystemLicenseInfo", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.GetSystemLicenseInfo")
    @ResponseWrapper(localName = "GetSystemLicenseInfoResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.GetSystemLicenseInfoResponse")
    @WebResult(name = "GetSystemLicenseInfoResult", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public com.mip.command.SystemLicenseInfo getSystemLicenseInfo()
;

    @WebMethod(operationName = "AlertsGetAroundWithSpan", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/AlertsGetAroundWithSpan")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/AlertsGetAroundWithSpan", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/AlertsGetAroundWithSpanResponse")
    @RequestWrapper(localName = "AlertsGetAroundWithSpan", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.AlertsGetAroundWithSpan")
    @ResponseWrapper(localName = "AlertsGetAroundWithSpanResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.AlertsGetAroundWithSpanResponse")
    @WebResult(name = "AlertsGetAroundWithSpanResult", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public com.mip.command.ArrayOfAlertOccurrence alertsGetAroundWithSpan(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "alertIds", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        com.mip.command.ArrayOfguid alertIds,
        @WebParam(name = "centerTime", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar centerTime,
        @WebParam(name = "maxTimeBefore", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        com.mip.command.TimeDuration maxTimeBefore,
        @WebParam(name = "maxCountBefore", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.Integer maxCountBefore,
        @WebParam(name = "maxTimeAfter", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        com.mip.command.TimeDuration maxTimeAfter,
        @WebParam(name = "maxCountAfter", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.Integer maxCountAfter
    );

    @WebMethod(operationName = "QueryChanges", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/QueryChanges")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/QueryChanges", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/QueryChangesResponse")
    @RequestWrapper(localName = "QueryChanges", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.QueryChanges")
    @ResponseWrapper(localName = "QueryChangesResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.QueryChangesResponse")
    @WebResult(name = "QueryChangesResult", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public com.mip.command.ArrayOfChange queryChanges(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "changesFrom", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar changesFrom
    );

    @WebMethod(operationName = "EventTrigger", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/EventTrigger")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/EventTrigger", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/EventTriggerResponse")
    @RequestWrapper(localName = "EventTrigger", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.EventTrigger")
    @ResponseWrapper(localName = "EventTriggerResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.EventTriggerResponse")
    public void eventTrigger(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "eventId", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String eventId
    );

    @WebMethod(operationName = "BookmarkSearchFromBookmark", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/BookmarkSearchFromBookmark")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/BookmarkSearchFromBookmark", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/BookmarkSearchFromBookmarkResponse")
    @RequestWrapper(localName = "BookmarkSearchFromBookmark", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.BookmarkSearchFromBookmark")
    @ResponseWrapper(localName = "BookmarkSearchFromBookmarkResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.BookmarkSearchFromBookmarkResponse")
    @WebResult(name = "BookmarkSearchFromBookmarkResult", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public com.mip.command.ArrayOfBookmark bookmarkSearchFromBookmark(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "fromBookmarkId", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String fromBookmarkId,
        @WebParam(name = "timeLimit", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        com.mip.command.TimeDuration timeLimit,
        @WebParam(name = "countLimit", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.Integer countLimit,
        @WebParam(name = "deviceTypes", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        com.mip.command.ArrayOfMediaDeviceType deviceTypes,
        @WebParam(name = "optDeviceIds", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        com.mip.command.ArrayOfguid optDeviceIds,
        @WebParam(name = "optUsers", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        com.mip.command.ArrayOfstring optUsers,
        @WebParam(name = "optSearchStr", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String optSearchStr
    );

    @WebMethod(operationName = "RegisterIntegration", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/RegisterIntegration")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/RegisterIntegration", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/RegisterIntegrationResponse")
    @RequestWrapper(localName = "RegisterIntegration", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.RegisterIntegration")
    @ResponseWrapper(localName = "RegisterIntegrationResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.RegisterIntegrationResponse")
    public void registerIntegration(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "instanceId", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String instanceId,
        @WebParam(name = "integrationId", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String integrationId,
        @WebParam(name = "integrationVersion", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String integrationVersion,
        @WebParam(name = "integrationName", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String integrationName,
        @WebParam(name = "manufacturerName", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String manufacturerName
    );

    @WebMethod(operationName = "MarkedDataDelete", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/MarkedDataDelete")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/MarkedDataDelete", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/MarkedDataDeleteResponse")
    @RequestWrapper(localName = "MarkedDataDelete", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.MarkedDataDelete")
    @ResponseWrapper(localName = "MarkedDataDeleteResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.MarkedDataDeleteResponse")
    @WebResult(name = "MarkedDataDeleteResult", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public com.mip.command.ArrayOfMarkedDataResult markedDataDelete(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "markedDataIds", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        com.mip.command.ArrayOfguid markedDataIds
    );

    @WebMethod(operationName = "MarkedDataGet", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/MarkedDataGet")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/MarkedDataGet", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/MarkedDataGetResponse")
    @RequestWrapper(localName = "MarkedDataGet", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.MarkedDataGet")
    @ResponseWrapper(localName = "MarkedDataGetResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.MarkedDataGetResponse")
    @WebResult(name = "MarkedDataGetResult", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public com.mip.command.MarkedData markedDataGet(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "markedDataId", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String markedDataId
    );

    @WebMethod(operationName = "Login", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/Login")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/Login", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/LoginResponse")
    @RequestWrapper(localName = "Login", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.Login")
    @ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.LoginResponse")
    @WebResult(name = "LoginResult", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public com.mip.command.LoginInfo login(

        @WebParam(name = "instanceId", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String instanceId,
        @WebParam(name = "currentToken", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String currentToken
    );

    @WebMethod(operationName = "GetCustomSettingDataGlobal2", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetCustomSettingDataGlobal2")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetCustomSettingDataGlobal2", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetCustomSettingDataGlobal2Response")
    @RequestWrapper(localName = "GetCustomSettingDataGlobal2", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.GetCustomSettingDataGlobal2")
    @ResponseWrapper(localName = "GetCustomSettingDataGlobal2Response", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.GetCustomSettingDataGlobal2Response")
    @WebResult(name = "GetCustomSettingDataGlobal2Result", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public com.mip.command.CustomSettingInternal getCustomSettingDataGlobal2(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "customSettingId", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String customSettingId
    );

    @WebMethod(operationName = "SetCustomSettingDataGlobal2", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/SetCustomSettingDataGlobal2")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/SetCustomSettingDataGlobal2", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/SetCustomSettingDataGlobal2Response")
    @RequestWrapper(localName = "SetCustomSettingDataGlobal2", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.SetCustomSettingDataGlobal2")
    @ResponseWrapper(localName = "SetCustomSettingDataGlobal2Response", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.SetCustomSettingDataGlobal2Response")
    @WebResult(name = "SetCustomSettingDataGlobal2Result", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public com.mip.command.SetCustomSettingResultType setCustomSettingDataGlobal2(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "customSettingId", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String customSettingId,
        @WebParam(name = "customSettingData", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        com.mip.command.CustomSettingInternalData customSettingData,
        @WebParam(name = "forceOverride", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.Boolean forceOverride
    );

    @WebMethod(operationName = "GetSmartClientVersion", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetSmartClientVersion")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetSmartClientVersion", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetSmartClientVersionResponse")
    @RequestWrapper(localName = "GetSmartClientVersion", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.GetSmartClientVersion")
    @ResponseWrapper(localName = "GetSmartClientVersionResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.GetSmartClientVersionResponse")
    @WebResult(name = "GetSmartClientVersionResult", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public com.mip.command.SmartClientVersion getSmartClientVersion()
;

    @WebMethod(operationName = "Authorize", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/Authorize")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/Authorize", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/AuthorizeResponse")
    @RequestWrapper(localName = "Authorize", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.Authorize")
    @ResponseWrapper(localName = "AuthorizeResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.AuthorizeResponse")
    @WebResult(name = "AuthorizeResult", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public java.lang.String authorize(

        @WebParam(name = "userDomainName", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String userDomainName,
        @WebParam(name = "type", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        com.mip.command.AuthorizationActionType type
    );

    @WebMethod(operationName = "UpdatePresetName", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/UpdatePresetName")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/UpdatePresetName", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/UpdatePresetNameResponse")
    @RequestWrapper(localName = "UpdatePresetName", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.UpdatePresetName")
    @ResponseWrapper(localName = "UpdatePresetNameResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.UpdatePresetNameResponse")
    public void updatePresetName(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "id", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String id,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String deviceId,
        @WebParam(name = "newName", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String newName
    );

    @WebMethod(operationName = "EventTriggerWithMetadata", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/EventTriggerWithMetadata")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/EventTriggerWithMetadata", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/EventTriggerWithMetadataResponse")
    @RequestWrapper(localName = "EventTriggerWithMetadata", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.EventTriggerWithMetadata")
    @ResponseWrapper(localName = "EventTriggerWithMetadataResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.EventTriggerWithMetadataResponse")
    public void eventTriggerWithMetadata(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "eventId", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String eventId,
        @WebParam(name = "metadata", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        com.mip.command.ArrayOfKeyValue metadata
    );

    @WebMethod(operationName = "SetViewGroupData", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/SetViewGroupData")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/SetViewGroupData", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/SetViewGroupDataResponse")
    @RequestWrapper(localName = "SetViewGroupData", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.SetViewGroupData")
    @ResponseWrapper(localName = "SetViewGroupDataResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.SetViewGroupDataResponse")
    @WebResult(name = "SetViewGroupDataResult", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public com.mip.command.SetViewGroupDataResultType setViewGroupData(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "viewGroupId", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String viewGroupId,
        @WebParam(name = "viewGroupdata", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        com.mip.command.ViewGroupInternalData viewGroupdata
    );

    @WebMethod(operationName = "GetDevicesDisabled", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetDevicesDisabled")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetDevicesDisabled", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetDevicesDisabledResponse")
    @RequestWrapper(localName = "GetDevicesDisabled", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.GetDevicesDisabled")
    @ResponseWrapper(localName = "GetDevicesDisabledResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.GetDevicesDisabledResponse")
    @WebResult(name = "GetDevicesDisabledResult", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public com.mip.command.ArrayOfDeviceDisabledInfo getDevicesDisabled(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token
    );

    @WebMethod(operationName = "BookmarkDelete", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/BookmarkDelete")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/BookmarkDelete", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/BookmarkDeleteResponse")
    @RequestWrapper(localName = "BookmarkDelete", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.BookmarkDelete")
    @ResponseWrapper(localName = "BookmarkDeleteResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.BookmarkDeleteResponse")
    public void bookmarkDelete(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "bookmarkId", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String bookmarkId
    );

    @WebMethod(operationName = "OrderPresets", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/OrderPresets")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/OrderPresets", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/OrderPresetsResponse")
    @RequestWrapper(localName = "OrderPresets", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.OrderPresets")
    @ResponseWrapper(localName = "OrderPresetsResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.OrderPresetsResponse")
    public void orderPresets(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String deviceId,
        @WebParam(name = "ids", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        com.mip.command.ArrayOfguid ids
    );

    @WebMethod(operationName = "BookmarkGet", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/BookmarkGet")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/BookmarkGet", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/BookmarkGetResponse")
    @RequestWrapper(localName = "BookmarkGet", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.BookmarkGet")
    @ResponseWrapper(localName = "BookmarkGetResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.BookmarkGetResponse")
    @WebResult(name = "BookmarkGetResult", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public com.mip.command.Bookmark bookmarkGet(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "bookmarkId", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String bookmarkId
    );

    @WebMethod(operationName = "GetUserInfo", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetUserInfo")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetUserInfo", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetUserInfoResponse")
    @RequestWrapper(localName = "GetUserInfo", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.GetUserInfo")
    @ResponseWrapper(localName = "GetUserInfoResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.GetUserInfoResponse")
    @WebResult(name = "GetUserInfoResult", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public com.mip.command.UserInfo getUserInfo(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token
    );

    @WebMethod(operationName = "GetCustomSettingDataUser2", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetCustomSettingDataUser2")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetCustomSettingDataUser2", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetCustomSettingDataUser2Response")
    @RequestWrapper(localName = "GetCustomSettingDataUser2", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.GetCustomSettingDataUser2")
    @ResponseWrapper(localName = "GetCustomSettingDataUser2Response", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.GetCustomSettingDataUser2Response")
    @WebResult(name = "GetCustomSettingDataUser2Result", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public com.mip.command.CustomSettingInternal getCustomSettingDataUser2(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "customSettingId", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String customSettingId
    );

    @WebMethod(operationName = "RegisterPluginIntegrations", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/RegisterPluginIntegrations")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/RegisterPluginIntegrations", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/RegisterPluginIntegrationsResponse")
    @RequestWrapper(localName = "RegisterPluginIntegrations", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.RegisterPluginIntegrations")
    @ResponseWrapper(localName = "RegisterPluginIntegrationsResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.RegisterPluginIntegrationsResponse")
    public void registerPluginIntegrations(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "instanceId", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String instanceId,
        @WebParam(name = "integrationType", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        com.mip.command.IntegrationType integrationType,
        @WebParam(name = "pluginIntegrations", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        com.mip.command.ArrayOfPluginIntegration pluginIntegrations
    );

    @WebMethod(operationName = "GetConfiguration", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetConfiguration")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetConfiguration", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/GetConfigurationResponse")
    @RequestWrapper(localName = "GetConfiguration", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.GetConfiguration")
    @ResponseWrapper(localName = "GetConfigurationResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.GetConfigurationResponse")
    @WebResult(name = "GetConfigurationResult", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
    public com.mip.command.ConfigurationInfo getConfiguration(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token
    );

    @WebMethod(operationName = "DeletePreset", action = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/DeletePreset")
    @Action(input = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/DeletePreset", output = "http://video.net/2/XProtectCSServerCommand/IServerCommandService/DeletePresetResponse")
    @RequestWrapper(localName = "DeletePreset", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.DeletePreset")
    @ResponseWrapper(localName = "DeletePresetResponse", targetNamespace = "http://video.net/2/XProtectCSServerCommand", className = "com.mip.command.DeletePresetResponse")
    public void deletePreset(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "id", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String id,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSServerCommand")
        java.lang.String deviceId
    );
}
