
package com.mip.command;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2021-11-02T20:25:00.358-07:00
 * Generated source version: 3.3.6
 *
 */
public final class IServerCommandService_WSHttpBindingIServerCommandService1_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "ServerCommandService");

    private IServerCommandService_WSHttpBindingIServerCommandService1_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ServerCommandService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ServerCommandService ss = new ServerCommandService(wsdlURL, SERVICE_NAME);
        IServerCommandService port = ss.getWSHttpBindingIServerCommandService1();

        {
        System.out.println("Invoking setCustomSettingDataGlobal...");
        java.lang.String _setCustomSettingDataGlobal_token = "";
        java.lang.String _setCustomSettingDataGlobal_customSettingId = "";
        com.mip.command.CustomSettingInternalData _setCustomSettingDataGlobal_customSettingData = null;
        java.lang.Boolean _setCustomSettingDataGlobal_forceOverride = null;
        com.mip.command.SetCustomSettingResultType _setCustomSettingDataGlobal__return = port.setCustomSettingDataGlobal(_setCustomSettingDataGlobal_token, _setCustomSettingDataGlobal_customSettingId, _setCustomSettingDataGlobal_customSettingData, _setCustomSettingDataGlobal_forceOverride);
        System.out.println("setCustomSettingDataGlobal.result=" + _setCustomSettingDataGlobal__return);


        }
        {
        System.out.println("Invoking getClientProfile3...");
        java.lang.String _getClientProfile3_token = "";
        java.lang.Boolean _getClientProfile3_withSetting = null;
        com.mip.command.ClientProfile _getClientProfile3__return = port.getClientProfile3(_getClientProfile3_token, _getClientProfile3_withSetting);
        System.out.println("getClientProfile3.result=" + _getClientProfile3__return);


        }
        {
        System.out.println("Invoking setCustomSettingDataUser...");
        java.lang.String _setCustomSettingDataUser_token = "";
        java.lang.String _setCustomSettingDataUser_customSettingId = "";
        com.mip.command.CustomSettingInternalData _setCustomSettingDataUser_customSettingData = null;
        java.lang.Boolean _setCustomSettingDataUser_forceOverride = null;
        com.mip.command.SetCustomSettingResultType _setCustomSettingDataUser__return = port.setCustomSettingDataUser(_setCustomSettingDataUser_token, _setCustomSettingDataUser_customSettingId, _setCustomSettingDataUser_customSettingData, _setCustomSettingDataUser_forceOverride);
        System.out.println("setCustomSettingDataUser.result=" + _setCustomSettingDataUser__return);


        }
        {
        System.out.println("Invoking getClientProfile2...");
        java.lang.String _getClientProfile2_token = "";
        java.lang.Boolean _getClientProfile2_withSetting = null;
        com.mip.command.ClientProfile _getClientProfile2__return = port.getClientProfile2(_getClientProfile2_token, _getClientProfile2_withSetting);
        System.out.println("getClientProfile2.result=" + _getClientProfile2__return);


        }
        {
        System.out.println("Invoking getServerVersion...");
        java.lang.String _getServerVersion__return = port.getServerVersion();
        System.out.println("getServerVersion.result=" + _getServerVersion__return);


        }
        {
        System.out.println("Invoking getViewGroupData...");
        java.lang.String _getViewGroupData_token = "";
        java.lang.String _getViewGroupData_viewGroupId = "";
        com.mip.command.ViewGroupInternal _getViewGroupData__return = port.getViewGroupData(_getViewGroupData_token, _getViewGroupData_viewGroupId);
        System.out.println("getViewGroupData.result=" + _getViewGroupData__return);


        }
        {
        System.out.println("Invoking markedDataCreate...");
        java.lang.String _markedDataCreate_token = "";
        java.lang.String _markedDataCreate_markedDataId = "";
        com.mip.command.ArrayOfguid _markedDataCreate_deviceIds = null;
        javax.xml.datatype.XMLGregorianCalendar _markedDataCreate_timeStart = null;
        javax.xml.datatype.XMLGregorianCalendar _markedDataCreate_timeTag = null;
        javax.xml.datatype.XMLGregorianCalendar _markedDataCreate_timeEnd = null;
        java.lang.String _markedDataCreate_reference = "";
        java.lang.String _markedDataCreate_header = "";
        java.lang.String _markedDataCreate_description = "";
        java.lang.Integer _markedDataCreate_markedDataType = null;
        java.lang.Boolean _markedDataCreate_useRetention = null;
        javax.xml.datatype.XMLGregorianCalendar _markedDataCreate_retentionExpire = null;
        com.mip.command.RetentionOption _markedDataCreate_retentionOption = null;
        com.mip.command.MarkedDataResult _markedDataCreate__return = port.markedDataCreate(_markedDataCreate_token, _markedDataCreate_markedDataId, _markedDataCreate_deviceIds, _markedDataCreate_timeStart, _markedDataCreate_timeTag, _markedDataCreate_timeEnd, _markedDataCreate_reference, _markedDataCreate_header, _markedDataCreate_description, _markedDataCreate_markedDataType, _markedDataCreate_useRetention, _markedDataCreate_retentionExpire, _markedDataCreate_retentionOption);
        System.out.println("markedDataCreate.result=" + _markedDataCreate__return);


        }
        {
        System.out.println("Invoking matrixMonitorActivateCamera...");
        java.lang.String _matrixMonitorActivateCamera_token = "";
        java.lang.String _matrixMonitorActivateCamera_matrixMonitorId = "";
        java.lang.String _matrixMonitorActivateCamera_deviceId = "";
        port.matrixMonitorActivateCamera(_matrixMonitorActivateCamera_token, _matrixMonitorActivateCamera_matrixMonitorId, _matrixMonitorActivateCamera_deviceId);


        }
        {
        System.out.println("Invoking updatePresetPosition...");
        java.lang.String _updatePresetPosition_token = "";
        java.lang.String _updatePresetPosition_id = "";
        java.lang.String _updatePresetPosition_deviceId = "";
        port.updatePresetPosition(_updatePresetPosition_token, _updatePresetPosition_id, _updatePresetPosition_deviceId);


        }
        {
        System.out.println("Invoking getCustomSettingDataUser...");
        java.lang.String _getCustomSettingDataUser_token = "";
        java.lang.String _getCustomSettingDataUser_customSettingId = "";
        com.mip.command.CustomSettingInternal _getCustomSettingDataUser__return = port.getCustomSettingDataUser(_getCustomSettingDataUser_token, _getCustomSettingDataUser_customSettingId);
        System.out.println("getCustomSettingDataUser.result=" + _getCustomSettingDataUser__return);


        }
        {
        System.out.println("Invoking getVersion...");
        java.lang.Integer _getVersion__return = port.getVersion();
        System.out.println("getVersion.result=" + _getVersion__return);


        }
        {
        System.out.println("Invoking logout...");
        java.lang.String _logout_instanceId = "";
        java.lang.String _logout_currentToken = "";
        port.logout(_logout_instanceId, _logout_currentToken);


        }
        {
        System.out.println("Invoking markedDataSearch...");
        java.lang.String _markedDataSearch_token = "";
        com.mip.command.ArrayOfguid _markedDataSearch_deviceIds = null;
        java.lang.String _markedDataSearch_searchText = "";
        com.mip.command.ArrayOfstring _markedDataSearch_users = null;
        javax.xml.datatype.XMLGregorianCalendar _markedDataSearch_createdFromTime = null;
        javax.xml.datatype.XMLGregorianCalendar _markedDataSearch_createdToTime = null;
        javax.xml.datatype.XMLGregorianCalendar _markedDataSearch_markedDataFromTime = null;
        javax.xml.datatype.XMLGregorianCalendar _markedDataSearch_markedDataToTime = null;
        javax.xml.datatype.XMLGregorianCalendar _markedDataSearch_tagTimeFromTime = null;
        javax.xml.datatype.XMLGregorianCalendar _markedDataSearch_tagTimeToTime = null;
        javax.xml.datatype.XMLGregorianCalendar _markedDataSearch_retentionExpireFrom = null;
        javax.xml.datatype.XMLGregorianCalendar _markedDataSearch_retentionExpireTo = null;
        java.lang.Integer _markedDataSearch_pageIndex = null;
        java.lang.Integer _markedDataSearch_pageSize = null;
        com.mip.command.SortOrderOption _markedDataSearch_sortOrder = null;
        java.lang.Boolean _markedDataSearch_sortAscending = null;
        com.mip.command.ArrayOfMarkedData _markedDataSearch__return = port.markedDataSearch(_markedDataSearch_token, _markedDataSearch_deviceIds, _markedDataSearch_searchText, _markedDataSearch_users, _markedDataSearch_createdFromTime, _markedDataSearch_createdToTime, _markedDataSearch_markedDataFromTime, _markedDataSearch_markedDataToTime, _markedDataSearch_tagTimeFromTime, _markedDataSearch_tagTimeToTime, _markedDataSearch_retentionExpireFrom, _markedDataSearch_retentionExpireTo, _markedDataSearch_pageIndex, _markedDataSearch_pageSize, _markedDataSearch_sortOrder, _markedDataSearch_sortAscending);
        System.out.println("markedDataSearch.result=" + _markedDataSearch__return);


        }
        {
        System.out.println("Invoking bookmarkCreate...");
        java.lang.String _bookmarkCreate_token = "";
        java.lang.String _bookmarkCreate_deviceId = "";
        javax.xml.datatype.XMLGregorianCalendar _bookmarkCreate_timeBegin = null;
        javax.xml.datatype.XMLGregorianCalendar _bookmarkCreate_timeTrigged = null;
        javax.xml.datatype.XMLGregorianCalendar _bookmarkCreate_timeEnd = null;
        java.lang.String _bookmarkCreate_reference = "";
        java.lang.String _bookmarkCreate_header = "";
        java.lang.String _bookmarkCreate_description = "";
        com.mip.command.Bookmark _bookmarkCreate__return = port.bookmarkCreate(_bookmarkCreate_token, _bookmarkCreate_deviceId, _bookmarkCreate_timeBegin, _bookmarkCreate_timeTrigged, _bookmarkCreate_timeEnd, _bookmarkCreate_reference, _bookmarkCreate_header, _bookmarkCreate_description);
        System.out.println("bookmarkCreate.result=" + _bookmarkCreate__return);


        }
        {
        System.out.println("Invoking getVmoServicesList...");
        com.mip.command.ArrayOfDictionaryEntry _getVmoServicesList__return = port.getVmoServicesList();
        System.out.println("getVmoServicesList.result=" + _getVmoServicesList__return);


        }
        {
        System.out.println("Invoking markedDataUpdate...");
        java.lang.String _markedDataUpdate_token = "";
        java.lang.String _markedDataUpdate_markedDataId = "";
        com.mip.command.ArrayOfguid _markedDataUpdate_deviceIds = null;
        javax.xml.datatype.XMLGregorianCalendar _markedDataUpdate_timeStart = null;
        javax.xml.datatype.XMLGregorianCalendar _markedDataUpdate_timeTag = null;
        javax.xml.datatype.XMLGregorianCalendar _markedDataUpdate_timeEnd = null;
        java.lang.String _markedDataUpdate_reference = "";
        java.lang.String _markedDataUpdate_header = "";
        java.lang.String _markedDataUpdate_description = "";
        java.lang.Integer _markedDataUpdate_markedDataType = null;
        java.lang.Boolean _markedDataUpdate_useRetention = null;
        javax.xml.datatype.XMLGregorianCalendar _markedDataUpdate_retentionExpire = null;
        com.mip.command.RetentionOption _markedDataUpdate_retentionOption = null;
        com.mip.command.MarkedDataResult _markedDataUpdate__return = port.markedDataUpdate(_markedDataUpdate_token, _markedDataUpdate_markedDataId, _markedDataUpdate_deviceIds, _markedDataUpdate_timeStart, _markedDataUpdate_timeTag, _markedDataUpdate_timeEnd, _markedDataUpdate_reference, _markedDataUpdate_header, _markedDataUpdate_description, _markedDataUpdate_markedDataType, _markedDataUpdate_useRetention, _markedDataUpdate_retentionExpire, _markedDataUpdate_retentionOption);
        System.out.println("markedDataUpdate.result=" + _markedDataUpdate__return);


        }
        {
        System.out.println("Invoking checkSmartClientVersion...");
        java.lang.Integer _checkSmartClientVersion_major = null;
        java.lang.Integer _checkSmartClientVersion_minor = null;
        java.lang.String _checkSmartClientVersion_revision = "";
        com.mip.command.SmartClientVersion _checkSmartClientVersion__return = port.checkSmartClientVersion(_checkSmartClientVersion_major, _checkSmartClientVersion_minor, _checkSmartClientVersion_revision);
        System.out.println("checkSmartClientVersion.result=" + _checkSmartClientVersion__return);


        }
        {
        System.out.println("Invoking getConfigurationHardware...");
        java.lang.String _getConfigurationHardware_token = "";
        com.mip.command.ArrayOfguid _getConfigurationHardware_hardwareIds = null;
        com.mip.command.ArrayOfHardwareInfo _getConfigurationHardware__return = port.getConfigurationHardware(_getConfigurationHardware_token, _getConfigurationHardware_hardwareIds);
        System.out.println("getConfigurationHardware.result=" + _getConfigurationHardware__return);


        }
        {
        System.out.println("Invoking getViewGroups...");
        java.lang.String _getViewGroups_token = "";
        com.mip.command.ArrayOfViewGroupInfo _getViewGroups__return = port.getViewGroups(_getViewGroups_token);
        System.out.println("getViewGroups.result=" + _getViewGroups__return);


        }
        {
        System.out.println("Invoking bookmarkGetNewReference...");
        java.lang.String _bookmarkGetNewReference_token = "";
        java.lang.String _bookmarkGetNewReference_deviceId = "";
        java.lang.Boolean _bookmarkGetNewReference_live = null;
        com.mip.command.BookmarkReference _bookmarkGetNewReference__return = port.bookmarkGetNewReference(_bookmarkGetNewReference_token, _bookmarkGetNewReference_deviceId, _bookmarkGetNewReference_live);
        System.out.println("bookmarkGetNewReference.result=" + _bookmarkGetNewReference__return);


        }
        {
        System.out.println("Invoking getPresets...");
        java.lang.String _getPresets_token = "";
        java.lang.String _getPresets_deviceId = "";
        com.mip.command.ArrayOfPresetInfo _getPresets__return = port.getPresets(_getPresets_token, _getPresets_deviceId);
        System.out.println("getPresets.result=" + _getPresets__return);


        }
        {
        System.out.println("Invoking bookmarkSearchTime...");
        java.lang.String _bookmarkSearchTime_token = "";
        javax.xml.datatype.XMLGregorianCalendar _bookmarkSearchTime_time = null;
        com.mip.command.TimeDuration _bookmarkSearchTime_timeLimit = null;
        java.lang.Integer _bookmarkSearchTime_countLimit = null;
        com.mip.command.ArrayOfMediaDeviceType _bookmarkSearchTime_deviceTypes = null;
        com.mip.command.ArrayOfguid _bookmarkSearchTime_optDeviceIds = null;
        com.mip.command.ArrayOfstring _bookmarkSearchTime_optUsers = null;
        java.lang.String _bookmarkSearchTime_optSearchStr = "";
        com.mip.command.ArrayOfBookmark _bookmarkSearchTime__return = port.bookmarkSearchTime(_bookmarkSearchTime_token, _bookmarkSearchTime_time, _bookmarkSearchTime_timeLimit, _bookmarkSearchTime_countLimit, _bookmarkSearchTime_deviceTypes, _bookmarkSearchTime_optDeviceIds, _bookmarkSearchTime_optUsers, _bookmarkSearchTime_optSearchStr);
        System.out.println("bookmarkSearchTime.result=" + _bookmarkSearchTime__return);


        }
        {
        System.out.println("Invoking markedDataGetNewReference...");
        java.lang.String _markedDataGetNewReference_token = "";
        com.mip.command.ArrayOfguid _markedDataGetNewReference_deviceId = null;
        java.lang.Boolean _markedDataGetNewReference_live = null;
        com.mip.command.MarkedDataReference _markedDataGetNewReference__return = port.markedDataGetNewReference(_markedDataGetNewReference_token, _markedDataGetNewReference_deviceId, _markedDataGetNewReference_live);
        System.out.println("markedDataGetNewReference.result=" + _markedDataGetNewReference__return);


        }
        {
        System.out.println("Invoking getClientProfile...");
        java.lang.String _getClientProfile_token = "";
        java.lang.Boolean _getClientProfile_withSetting = null;
        com.mip.command.ClientProfile _getClientProfile__return = port.getClientProfile(_getClientProfile_token, _getClientProfile_withSetting);
        System.out.println("getClientProfile.result=" + _getClientProfile__return);


        }
        {
        System.out.println("Invoking bookmarkUpdate...");
        java.lang.String _bookmarkUpdate_token = "";
        java.lang.String _bookmarkUpdate_bookmarkId = "";
        java.lang.String _bookmarkUpdate_deviceId = "";
        javax.xml.datatype.XMLGregorianCalendar _bookmarkUpdate_timeBegin = null;
        javax.xml.datatype.XMLGregorianCalendar _bookmarkUpdate_timeTrigged = null;
        javax.xml.datatype.XMLGregorianCalendar _bookmarkUpdate_timeEnd = null;
        java.lang.String _bookmarkUpdate_reference = "";
        java.lang.String _bookmarkUpdate_header = "";
        java.lang.String _bookmarkUpdate_description = "";
        com.mip.command.Bookmark _bookmarkUpdate__return = port.bookmarkUpdate(_bookmarkUpdate_token, _bookmarkUpdate_bookmarkId, _bookmarkUpdate_deviceId, _bookmarkUpdate_timeBegin, _bookmarkUpdate_timeTrigged, _bookmarkUpdate_timeEnd, _bookmarkUpdate_reference, _bookmarkUpdate_header, _bookmarkUpdate_description);
        System.out.println("bookmarkUpdate.result=" + _bookmarkUpdate__return);


        }
        {
        System.out.println("Invoking getProductInfo...");
        com.mip.command.ProductInfo _getProductInfo__return = port.getProductInfo();
        System.out.println("getProductInfo.result=" + _getProductInfo__return);


        }
        {
        System.out.println("Invoking setCustomSettingDataUser2...");
        java.lang.String _setCustomSettingDataUser2_token = "";
        java.lang.String _setCustomSettingDataUser2_customSettingId = "";
        com.mip.command.CustomSettingInternalData _setCustomSettingDataUser2_customSettingData = null;
        java.lang.Boolean _setCustomSettingDataUser2_forceOverride = null;
        com.mip.command.SetCustomSettingResultType _setCustomSettingDataUser2__return = port.setCustomSettingDataUser2(_setCustomSettingDataUser2_token, _setCustomSettingDataUser2_customSettingId, _setCustomSettingDataUser2_customSettingData, _setCustomSettingDataUser2_forceOverride);
        System.out.println("setCustomSettingDataUser2.result=" + _setCustomSettingDataUser2__return);


        }
        {
        System.out.println("Invoking createPreset...");
        java.lang.String _createPreset_token = "";
        java.lang.String _createPreset_deviceId = "";
        java.lang.String _createPreset_name = "";
        java.lang.String _createPreset__return = port.createPreset(_createPreset_token, _createPreset_deviceId, _createPreset_name);
        System.out.println("createPreset.result=" + _createPreset__return);


        }
        {
        System.out.println("Invoking isOnline...");
        java.lang.Boolean _isOnline__return = port.isOnline();
        System.out.println("isOnline.result=" + _isOnline__return);


        }
        {
        System.out.println("Invoking queryRecorderInfo...");
        java.lang.String _queryRecorderInfo_token = "";
        java.lang.String _queryRecorderInfo_recorderId = "";
        com.mip.command.RecorderInfo _queryRecorderInfo__return = port.queryRecorderInfo(_queryRecorderInfo_token, _queryRecorderInfo_recorderId);
        System.out.println("queryRecorderInfo.result=" + _queryRecorderInfo__return);


        }
        {
        System.out.println("Invoking getCustomSettingDataGlobal...");
        java.lang.String _getCustomSettingDataGlobal_token = "";
        java.lang.String _getCustomSettingDataGlobal_customSettingId = "";
        com.mip.command.CustomSettingInternal _getCustomSettingDataGlobal__return = port.getCustomSettingDataGlobal(_getCustomSettingDataGlobal_token, _getCustomSettingDataGlobal_customSettingId);
        System.out.println("getCustomSettingDataGlobal.result=" + _getCustomSettingDataGlobal__return);


        }
        {
        System.out.println("Invoking getConfigurationRecorders...");
        java.lang.String _getConfigurationRecorders_token = "";
        com.mip.command.ArrayOfguid _getConfigurationRecorders_recorderIds = null;
        com.mip.command.ArrayOfRecorderInfo _getConfigurationRecorders__return = port.getConfigurationRecorders(_getConfigurationRecorders_token, _getConfigurationRecorders_recorderIds);
        System.out.println("getConfigurationRecorders.result=" + _getConfigurationRecorders__return);


        }
        {
        System.out.println("Invoking getSystemLicenseInfo...");
        com.mip.command.SystemLicenseInfo _getSystemLicenseInfo__return = port.getSystemLicenseInfo();
        System.out.println("getSystemLicenseInfo.result=" + _getSystemLicenseInfo__return);


        }
        {
        System.out.println("Invoking alertsGetAroundWithSpan...");
        java.lang.String _alertsGetAroundWithSpan_token = "";
        com.mip.command.ArrayOfguid _alertsGetAroundWithSpan_alertIds = null;
        javax.xml.datatype.XMLGregorianCalendar _alertsGetAroundWithSpan_centerTime = null;
        com.mip.command.TimeDuration _alertsGetAroundWithSpan_maxTimeBefore = null;
        java.lang.Integer _alertsGetAroundWithSpan_maxCountBefore = null;
        com.mip.command.TimeDuration _alertsGetAroundWithSpan_maxTimeAfter = null;
        java.lang.Integer _alertsGetAroundWithSpan_maxCountAfter = null;
        com.mip.command.ArrayOfAlertOccurrence _alertsGetAroundWithSpan__return = port.alertsGetAroundWithSpan(_alertsGetAroundWithSpan_token, _alertsGetAroundWithSpan_alertIds, _alertsGetAroundWithSpan_centerTime, _alertsGetAroundWithSpan_maxTimeBefore, _alertsGetAroundWithSpan_maxCountBefore, _alertsGetAroundWithSpan_maxTimeAfter, _alertsGetAroundWithSpan_maxCountAfter);
        System.out.println("alertsGetAroundWithSpan.result=" + _alertsGetAroundWithSpan__return);


        }
        {
        System.out.println("Invoking queryChanges...");
        java.lang.String _queryChanges_token = "";
        javax.xml.datatype.XMLGregorianCalendar _queryChanges_changesFrom = null;
        com.mip.command.ArrayOfChange _queryChanges__return = port.queryChanges(_queryChanges_token, _queryChanges_changesFrom);
        System.out.println("queryChanges.result=" + _queryChanges__return);


        }
        {
        System.out.println("Invoking eventTrigger...");
        java.lang.String _eventTrigger_token = "";
        java.lang.String _eventTrigger_eventId = "";
        port.eventTrigger(_eventTrigger_token, _eventTrigger_eventId);


        }
        {
        System.out.println("Invoking bookmarkSearchFromBookmark...");
        java.lang.String _bookmarkSearchFromBookmark_token = "";
        java.lang.String _bookmarkSearchFromBookmark_fromBookmarkId = "";
        com.mip.command.TimeDuration _bookmarkSearchFromBookmark_timeLimit = null;
        java.lang.Integer _bookmarkSearchFromBookmark_countLimit = null;
        com.mip.command.ArrayOfMediaDeviceType _bookmarkSearchFromBookmark_deviceTypes = null;
        com.mip.command.ArrayOfguid _bookmarkSearchFromBookmark_optDeviceIds = null;
        com.mip.command.ArrayOfstring _bookmarkSearchFromBookmark_optUsers = null;
        java.lang.String _bookmarkSearchFromBookmark_optSearchStr = "";
        com.mip.command.ArrayOfBookmark _bookmarkSearchFromBookmark__return = port.bookmarkSearchFromBookmark(_bookmarkSearchFromBookmark_token, _bookmarkSearchFromBookmark_fromBookmarkId, _bookmarkSearchFromBookmark_timeLimit, _bookmarkSearchFromBookmark_countLimit, _bookmarkSearchFromBookmark_deviceTypes, _bookmarkSearchFromBookmark_optDeviceIds, _bookmarkSearchFromBookmark_optUsers, _bookmarkSearchFromBookmark_optSearchStr);
        System.out.println("bookmarkSearchFromBookmark.result=" + _bookmarkSearchFromBookmark__return);


        }
        {
        System.out.println("Invoking registerIntegration...");
        java.lang.String _registerIntegration_token = "";
        java.lang.String _registerIntegration_instanceId = "";
        java.lang.String _registerIntegration_integrationId = "";
        java.lang.String _registerIntegration_integrationVersion = "";
        java.lang.String _registerIntegration_integrationName = "";
        java.lang.String _registerIntegration_manufacturerName = "";
        port.registerIntegration(_registerIntegration_token, _registerIntegration_instanceId, _registerIntegration_integrationId, _registerIntegration_integrationVersion, _registerIntegration_integrationName, _registerIntegration_manufacturerName);


        }
        {
        System.out.println("Invoking markedDataDelete...");
        java.lang.String _markedDataDelete_token = "";
        com.mip.command.ArrayOfguid _markedDataDelete_markedDataIds = null;
        com.mip.command.ArrayOfMarkedDataResult _markedDataDelete__return = port.markedDataDelete(_markedDataDelete_token, _markedDataDelete_markedDataIds);
        System.out.println("markedDataDelete.result=" + _markedDataDelete__return);


        }
        {
        System.out.println("Invoking markedDataGet...");
        java.lang.String _markedDataGet_token = "";
        java.lang.String _markedDataGet_markedDataId = "";
        com.mip.command.MarkedData _markedDataGet__return = port.markedDataGet(_markedDataGet_token, _markedDataGet_markedDataId);
        System.out.println("markedDataGet.result=" + _markedDataGet__return);


        }
        {
        System.out.println("Invoking login...");
        java.lang.String _login_instanceId = "";
        java.lang.String _login_currentToken = "";
        com.mip.command.LoginInfo _login__return = port.login(_login_instanceId, _login_currentToken);
        System.out.println("login.result=" + _login__return);


        }
        {
        System.out.println("Invoking getCustomSettingDataGlobal2...");
        java.lang.String _getCustomSettingDataGlobal2_token = "";
        java.lang.String _getCustomSettingDataGlobal2_customSettingId = "";
        com.mip.command.CustomSettingInternal _getCustomSettingDataGlobal2__return = port.getCustomSettingDataGlobal2(_getCustomSettingDataGlobal2_token, _getCustomSettingDataGlobal2_customSettingId);
        System.out.println("getCustomSettingDataGlobal2.result=" + _getCustomSettingDataGlobal2__return);


        }
        {
        System.out.println("Invoking setCustomSettingDataGlobal2...");
        java.lang.String _setCustomSettingDataGlobal2_token = "";
        java.lang.String _setCustomSettingDataGlobal2_customSettingId = "";
        com.mip.command.CustomSettingInternalData _setCustomSettingDataGlobal2_customSettingData = null;
        java.lang.Boolean _setCustomSettingDataGlobal2_forceOverride = null;
        com.mip.command.SetCustomSettingResultType _setCustomSettingDataGlobal2__return = port.setCustomSettingDataGlobal2(_setCustomSettingDataGlobal2_token, _setCustomSettingDataGlobal2_customSettingId, _setCustomSettingDataGlobal2_customSettingData, _setCustomSettingDataGlobal2_forceOverride);
        System.out.println("setCustomSettingDataGlobal2.result=" + _setCustomSettingDataGlobal2__return);


        }
        {
        System.out.println("Invoking getSmartClientVersion...");
        com.mip.command.SmartClientVersion _getSmartClientVersion__return = port.getSmartClientVersion();
        System.out.println("getSmartClientVersion.result=" + _getSmartClientVersion__return);


        }
        {
        System.out.println("Invoking authorize...");
        java.lang.String _authorize_userDomainName = "";
        com.mip.command.AuthorizationActionType _authorize_type = null;
        java.lang.String _authorize__return = port.authorize(_authorize_userDomainName, _authorize_type);
        System.out.println("authorize.result=" + _authorize__return);


        }
        {
        System.out.println("Invoking updatePresetName...");
        java.lang.String _updatePresetName_token = "";
        java.lang.String _updatePresetName_id = "";
        java.lang.String _updatePresetName_deviceId = "";
        java.lang.String _updatePresetName_newName = "";
        port.updatePresetName(_updatePresetName_token, _updatePresetName_id, _updatePresetName_deviceId, _updatePresetName_newName);


        }
        {
        System.out.println("Invoking eventTriggerWithMetadata...");
        java.lang.String _eventTriggerWithMetadata_token = "";
        java.lang.String _eventTriggerWithMetadata_eventId = "";
        com.mip.command.ArrayOfKeyValue _eventTriggerWithMetadata_metadata = null;
        port.eventTriggerWithMetadata(_eventTriggerWithMetadata_token, _eventTriggerWithMetadata_eventId, _eventTriggerWithMetadata_metadata);


        }
        {
        System.out.println("Invoking setViewGroupData...");
        java.lang.String _setViewGroupData_token = "";
        java.lang.String _setViewGroupData_viewGroupId = "";
        com.mip.command.ViewGroupInternalData _setViewGroupData_viewGroupdata = null;
        com.mip.command.SetViewGroupDataResultType _setViewGroupData__return = port.setViewGroupData(_setViewGroupData_token, _setViewGroupData_viewGroupId, _setViewGroupData_viewGroupdata);
        System.out.println("setViewGroupData.result=" + _setViewGroupData__return);


        }
        {
        System.out.println("Invoking getDevicesDisabled...");
        java.lang.String _getDevicesDisabled_token = "";
        com.mip.command.ArrayOfDeviceDisabledInfo _getDevicesDisabled__return = port.getDevicesDisabled(_getDevicesDisabled_token);
        System.out.println("getDevicesDisabled.result=" + _getDevicesDisabled__return);


        }
        {
        System.out.println("Invoking bookmarkDelete...");
        java.lang.String _bookmarkDelete_token = "";
        java.lang.String _bookmarkDelete_bookmarkId = "";
        port.bookmarkDelete(_bookmarkDelete_token, _bookmarkDelete_bookmarkId);


        }
        {
        System.out.println("Invoking orderPresets...");
        java.lang.String _orderPresets_token = "";
        java.lang.String _orderPresets_deviceId = "";
        com.mip.command.ArrayOfguid _orderPresets_ids = null;
        port.orderPresets(_orderPresets_token, _orderPresets_deviceId, _orderPresets_ids);


        }
        {
        System.out.println("Invoking bookmarkGet...");
        java.lang.String _bookmarkGet_token = "";
        java.lang.String _bookmarkGet_bookmarkId = "";
        com.mip.command.Bookmark _bookmarkGet__return = port.bookmarkGet(_bookmarkGet_token, _bookmarkGet_bookmarkId);
        System.out.println("bookmarkGet.result=" + _bookmarkGet__return);


        }
        {
        System.out.println("Invoking getUserInfo...");
        java.lang.String _getUserInfo_token = "";
        com.mip.command.UserInfo _getUserInfo__return = port.getUserInfo(_getUserInfo_token);
        System.out.println("getUserInfo.result=" + _getUserInfo__return);


        }
        {
        System.out.println("Invoking getCustomSettingDataUser2...");
        java.lang.String _getCustomSettingDataUser2_token = "";
        java.lang.String _getCustomSettingDataUser2_customSettingId = "";
        com.mip.command.CustomSettingInternal _getCustomSettingDataUser2__return = port.getCustomSettingDataUser2(_getCustomSettingDataUser2_token, _getCustomSettingDataUser2_customSettingId);
        System.out.println("getCustomSettingDataUser2.result=" + _getCustomSettingDataUser2__return);


        }
        {
        System.out.println("Invoking registerPluginIntegrations...");
        java.lang.String _registerPluginIntegrations_token = "";
        java.lang.String _registerPluginIntegrations_instanceId = "";
        com.mip.command.IntegrationType _registerPluginIntegrations_integrationType = null;
        com.mip.command.ArrayOfPluginIntegration _registerPluginIntegrations_pluginIntegrations = null;
        port.registerPluginIntegrations(_registerPluginIntegrations_token, _registerPluginIntegrations_instanceId, _registerPluginIntegrations_integrationType, _registerPluginIntegrations_pluginIntegrations);


        }
        {
        System.out.println("Invoking getConfiguration...");
        java.lang.String _getConfiguration_token = "";
        com.mip.command.ConfigurationInfo _getConfiguration__return = port.getConfiguration(_getConfiguration_token);
        System.out.println("getConfiguration.result=" + _getConfiguration__return);


        }
        {
        System.out.println("Invoking deletePreset...");
        java.lang.String _deletePreset_token = "";
        java.lang.String _deletePreset_id = "";
        java.lang.String _deletePreset_deviceId = "";
        port.deletePreset(_deletePreset_token, _deletePreset_id, _deletePreset_deviceId);


        }

        System.exit(0);
    }

}
