package com.mip.command;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2021-11-02T20:25:00.423-07:00
 * Generated source version: 3.3.6
 *
 */
@WebServiceClient(name = "ServerCommandService",
                  wsdlLocation = "file:/home/denis/Work/ISC/isc-web/isc-main/isc-integration-mip/src/main/resources/wsdl/ServerCommandService.wsdl",
                  targetNamespace = "http://tempuri.org/")
public class ServerCommandService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "ServerCommandService");
    public final static QName BasicHttpBindingIServerCommandService = new QName("http://tempuri.org/", "BasicHttpBinding_IServerCommandService");
    public final static QName WSHttpBindingIServerCommandService1 = new QName("http://tempuri.org/", "WSHttpBinding_IServerCommandService1");
    public final static QName WSHttpBindingIServerCommandService = new QName("http://tempuri.org/", "WSHttpBinding_IServerCommandService");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/denis/Work/ISC/isc-web/isc-main/isc-integration-mip/src/main/resources/wsdl/ServerCommandService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServerCommandService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/home/denis/Work/ISC/isc-web/isc-main/isc-integration-mip/src/main/resources/wsdl/ServerCommandService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServerCommandService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServerCommandService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServerCommandService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ServerCommandService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ServerCommandService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ServerCommandService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IServerCommandService
     */
    @WebEndpoint(name = "BasicHttpBinding_IServerCommandService")
    public IServerCommandService getBasicHttpBindingIServerCommandService() {
        return super.getPort(BasicHttpBindingIServerCommandService, IServerCommandService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IServerCommandService
     */
    @WebEndpoint(name = "BasicHttpBinding_IServerCommandService")
    public IServerCommandService getBasicHttpBindingIServerCommandService(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIServerCommandService, IServerCommandService.class, features);
    }


    /**
     *
     * @return
     *     returns IServerCommandService
     */
    @WebEndpoint(name = "WSHttpBinding_IServerCommandService1")
    public IServerCommandService getWSHttpBindingIServerCommandService1() {
        return super.getPort(WSHttpBindingIServerCommandService1, IServerCommandService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IServerCommandService
     */
    @WebEndpoint(name = "WSHttpBinding_IServerCommandService1")
    public IServerCommandService getWSHttpBindingIServerCommandService1(WebServiceFeature... features) {
        return super.getPort(WSHttpBindingIServerCommandService1, IServerCommandService.class, features);
    }


    /**
     *
     * @return
     *     returns IServerCommandService
     */
    @WebEndpoint(name = "WSHttpBinding_IServerCommandService")
    public IServerCommandService getWSHttpBindingIServerCommandService() {
        return super.getPort(WSHttpBindingIServerCommandService, IServerCommandService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IServerCommandService
     */
    @WebEndpoint(name = "WSHttpBinding_IServerCommandService")
    public IServerCommandService getWSHttpBindingIServerCommandService(WebServiceFeature... features) {
        return super.getPort(WSHttpBindingIServerCommandService, IServerCommandService.class, features);
    }

}
