version: '3.3'

services:
  isc-elasticsearch:
    image: nexus.iscweb.io:5002/isc-elasticsearch:latest
    container_name: isc-elasticsearch
    volumes:
      - type: bind
        source: /opt/isc-data/isc-elasticsearch
        target: /usr/share/elasticsearch/data
      - type: bind
        source: /opt/isc-logs/isc-elasticsearch
        target: /usr/share/elasticsearch/logs
      - type: bind
        source: /opt/isc-backup/isc-elasticsearch
        target: /usr/share/elasticsearch/backup
      - type: bind
        source: conf/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - TARGET_ENV=local
