---
include:
  - local: isc-env/docker/.gitlab-ci-common.yml

stages:
  - gradle-build
  - docker-build
  - ansible-deploy

gradle-build:
  stage: gradle-build
  extends: .gradle-build
  variables:
    CI: "false"
  script:
    - curl -sL https://rpm.nodesource.com/setup_12.x | bash -
    - yum install -y nodejs
    - node --version
    - curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo --output /etc/yum.repos.d/yarn.repo
    - rpm --import https://dl.yarnpkg.com/rpm/pubkey.gpg
    - yum install -y yarn
    - yarn --version
    - cd isc-main
    - ./gradlew --build-cache cBuild
  # cache:
  #   key: ${CI_COMMIT_REF_NAME}-${APP_NAME}
  #   policy: pull-push
  #   paths:
  #     - isc-main/isc-client/node_modules/
  #     - isc-main/isc-client/yarn.lock
  artifacts:
    paths:
      - isc-env/docker/${APP_NAME}/artifacts/*
    expire_in: 7 days

# gradle-build:
#   stage: gradle-build
#   image: node:12
#   tags:
#     - docker_spot_runner
#   script:
#     - cd isc-main/isc-client
#     - yarn install
#     - yarn build
#     - mv build ../../isc-env/docker/${APP_NAME}/artifacts/
#   cache:
#     key: ${CI_COMMIT_REF_NAME}-${APP_NAME}
#     policy: pull-push
#     paths:
#       - isc-main/isc-client/node_modules/
#       - isc-main/isc-client/yarn.lock
#   artifacts:
#     paths:
#       - isc-env/docker/${APP_NAME}/artifacts/*
#     expire_in: 7 days

docker-build:
  stage: docker-build
  extends: .docker-build
  needs:
    - job: gradle-build

ansible-deploy-dev:
  stage: ansible-deploy
  extends: .ansible-deploy
  needs:
    - job: docker-build
  except:
    - prod

ansible-deploy-prod:
  stage: ansible-deploy
  extends: .ansible-deploy-prod
  needs:
    - job: docker-build
  only:
    - prod
