version: '3.3'

services:
  isc-logstash-youtube-videos:
    image: local/isc-logstash-youtube-videos:latest
    container_name: isc-logstash-youtube-videos
    volumes:
      - type: bind
        source: ./conf/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
      - type: bind
        source: /tmp/isc-data/isc-logstash-youtube-videos
        target: /out
    environment:
      - TARGET_ENV=local

      - YOUTUBE_SEARCH_KEY=Q_E
      - YOUTUBE_SEARCH_MAX=10
      - YOUTUBE_SEARCH_QUERY=school

      - YOUTUBE_COMMENTS_KEY=Q6wqX0
      - YOUTUBE_COMMENTS_MAX=50
