version: '3.3'

networks:
  default:
    name: isc-network

services:
  isc-standalone-chrome:
    image: west-1.amazonaws.com/selenium/standalone-chrome:88.0.4324.150
    container_name: standalone-chrome
    ports:
      - 4444:4444
    volumes:
      - type: bind
        source: /dev/shm
        target: /dev/shm
