---
- name: config - Setup monitrc
  template:
    src: monitrc.j2
    dest: /etc/monit/monitrc
    owner: root
    group: root
    mode: 0700
  notify: restart monit

- name: config - Setup httpd
  template:
    src: httpd.j2
    dest: "{{ monit_conf_dir }}/httpd"
    owner: root
    group: root
    mode: 0644
  notify: restart monit
  when: monit_httpd_enabled

- name: config - Remove httpd
  file:
    path: "{{ monit_conf_dir }}/httpd"
    state: absent
  notify: restart monit
  when: not monit_httpd_enabled

- name: config - Setup mail alerts
  template:
    src: mail.j2
    dest: "{{ monit_conf_dir }}/mail"
    owner: root
    group: root
    mode: 0644
  notify: restart monit
  when: monit_mail_enabled

- name: config - Remove mail alerts
  file:
    path: "{{ monit_conf_dir }}/mail"
    state: absent
  notify: restart monit
  when: not monit_mail_enabled
