---
# defaults file for docker
docker_ce_requirements:
  - apt-transport-https
  - ca-certificates
  - gnupg2
  - software-properties-common

docker_ce_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io

docker_pip_packages:
  - docker
  - docker-compose

docker_ce_apt_key_url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
docker_ce_apt_repository_repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"

docker_ce_service: docker

# Docker Compose options
docker_install_compose: true
docker_compose_version: "1.28.4"
docker_compose_path: /usr/local/bin/docker-compose

# A list of users who will be added to the docker group.
docker_users: []
