package com.mip.alarmService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2021-11-02T20:25:08.620-07:00
 * Generated source version: 3.3.6
 *
 */
@WebServiceClient(name = "AlarmCommandToken",
                  wsdlLocation = "file:/home/denis/Work/ISC/isc-web/isc-main/isc-integration-mip/src/main/resources/wsdl/AlarmServiceToken.wsdl",
                  targetNamespace = "http://tempuri.org/")
public class AlarmCommandToken extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "AlarmCommandToken");
    public final static QName BasicHttpBindingIAlarmCommandToken = new QName("http://tempuri.org/", "BasicHttpBinding_IAlarmCommandToken");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/denis/Work/ISC/isc-web/isc-main/isc-integration-mip/src/main/resources/wsdl/AlarmServiceToken.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AlarmCommandToken.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/home/denis/Work/ISC/isc-web/isc-main/isc-integration-mip/src/main/resources/wsdl/AlarmServiceToken.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AlarmCommandToken(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AlarmCommandToken(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AlarmCommandToken() {
        super(WSDL_LOCATION, SERVICE);
    }

    public AlarmCommandToken(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AlarmCommandToken(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AlarmCommandToken(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IAlarmCommandToken
     */
    @WebEndpoint(name = "BasicHttpBinding_IAlarmCommandToken")
    public IAlarmCommandToken getBasicHttpBindingIAlarmCommandToken() {
        return super.getPort(BasicHttpBindingIAlarmCommandToken, IAlarmCommandToken.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IAlarmCommandToken
     */
    @WebEndpoint(name = "BasicHttpBinding_IAlarmCommandToken")
    public IAlarmCommandToken getBasicHttpBindingIAlarmCommandToken(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIAlarmCommandToken, IAlarmCommandToken.class, features);
    }

}
