---
- name: ISC-App
  hosts: isc_app
  remote_user: "{{ isc_username }}"
  become: yes
  gather_facts: false

  vars:
    container_name: isc-app

  tasks:
    - name: Create target directory
      file:
        path: "{{ isc_docker_home }}/{{ container_name }}/artifacts"
        state: directory
        owner: "{{ isc_username }}"
        group: docker
        mode: 0755

    - name: Create mock videos directory
      file:
        path: "{{ isc_data_home }}/isc-mock-videos"
        state: directory
        owner: "{{ isc_username }}"
        group: "{{ isc_username }}"
        mode: 0755

    - name: Copy application.yaml configuration file to the remote server
      template:
        src: "{{ job_home }}/isc-wormhole-{{ env_name }}/{{ container_name }}/{{ env_name }}.application.yml"
        dest: "{{ isc_docker_home }}/{{ container_name }}/artifacts/application.yml"
        owner: "{{ isc_username }}"
        group: docker
        mode: 0750
        # force: yes

    - name: Copy isc-app directory
      copy:
        src: isc-app
        dest: /tmp
        owner: "{{ isc_username }}"
        group: "{{ isc_username }}"
        mode: 0640

    - name: Copy initiation script
      template:
        src: isc-app/init_all.sh
        dest: /tmp/isc-app/init_all.sh
        owner: "{{ isc_username }}"
        group: "{{ isc_username }}"
        mode: 0755
        # force: yes

    - name: Execute initiation script
      command: chdir=/tmp/isc-app ./init_all.sh

    - import_tasks: common/isc_docker_deployment.yml
