---
- name: ISC-Elasticsearch
  hosts: isc_elasticsearch
  remote_user: "{{ isc_username }}"
  become: yes
  gather_facts: false

  vars:
    container_name: isc-elasticsearch

  tasks:
    - name: Create shared data directory
      file:
        path: "{{ isc_data_home }}/{{ container_name }}"
        state: directory
        owner: ubuntu
        group: root
        mode: 0755

    - name: Create backup directory
      file:
        path: "{{ isc_backup_home }}/{{ container_name }}"
        state: directory
        owner: "{{ isc_username }}"
        group: "{{ isc_username }}"
        mode: 0755

    - import_tasks: common/isc_docker_deployment.yml
