package com.mip.recorderStatus;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2021-11-02T20:25:06.271-07:00
 * Generated source version: 3.3.6
 *
 */
@WebServiceClient(name = "RecorderStatusService2",
                  wsdlLocation = "file:/home/denis/Work/ISC/isc-web/isc-main/isc-integration-mip/src/main/resources/wsdl/RecorderStatusService.wsdl",
                  targetNamespace = "http://video.net/2/XProtectCSRecorderStatus2")
public class RecorderStatusService2 extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://video.net/2/XProtectCSRecorderStatus2", "RecorderStatusService2");
    public final static QName RecorderStatusService2Soap = new QName("http://video.net/2/XProtectCSRecorderStatus2", "RecorderStatusService2Soap");
    public final static QName RecorderStatusService2Soap12 = new QName("http://video.net/2/XProtectCSRecorderStatus2", "RecorderStatusService2Soap12");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/denis/Work/ISC/isc-web/isc-main/isc-integration-mip/src/main/resources/wsdl/RecorderStatusService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RecorderStatusService2.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/home/denis/Work/ISC/isc-web/isc-main/isc-integration-mip/src/main/resources/wsdl/RecorderStatusService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RecorderStatusService2(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RecorderStatusService2(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RecorderStatusService2() {
        super(WSDL_LOCATION, SERVICE);
    }

    public RecorderStatusService2(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public RecorderStatusService2(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public RecorderStatusService2(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns RecorderStatusService2Soap
     */
    @WebEndpoint(name = "RecorderStatusService2Soap")
    public RecorderStatusService2Soap getRecorderStatusService2Soap() {
        return super.getPort(RecorderStatusService2Soap, RecorderStatusService2Soap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RecorderStatusService2Soap
     */
    @WebEndpoint(name = "RecorderStatusService2Soap")
    public RecorderStatusService2Soap getRecorderStatusService2Soap(WebServiceFeature... features) {
        return super.getPort(RecorderStatusService2Soap, RecorderStatusService2Soap.class, features);
    }


    /**
     *
     * @return
     *     returns RecorderStatusService2Soap
     */
    @WebEndpoint(name = "RecorderStatusService2Soap12")
    public RecorderStatusService2Soap getRecorderStatusService2Soap12() {
        return super.getPort(RecorderStatusService2Soap12, RecorderStatusService2Soap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RecorderStatusService2Soap
     */
    @WebEndpoint(name = "RecorderStatusService2Soap12")
    public RecorderStatusService2Soap getRecorderStatusService2Soap12(WebServiceFeature... features) {
        return super.getPort(RecorderStatusService2Soap12, RecorderStatusService2Soap.class, features);
    }

}
