package com.iscweb.integration.cameras.mip.dto;

/**
 * All know item type we can get information about from IConfigurationService :: getItem or GetChildItem methods
 */
public enum MipConfigItemTypes {
    System,
    RecordingServer,
    RecordingServerFolder,
    HardwareDriverFolder,
    HardwareDriver,
    Hardware,
    HardwareFolder,
    CameraFolder,
    InputEventFolder,
    OutputFolder,
    MicrophoneFolder,
    SpeakerFolder,
    MetadataFolder,
    Camera,
    InputEvent,
    Output,
    Microphone,
    Speaker,
    Metadata,
    CameraGroup,
    CameraGroupFolder,
    MetadataGroup,
    MetadataGroupFolder,
    MicrophoneGroup,
    MicrophoneGroupFolder,
    SpeakerGroup,
    SpeakerGroupFolder,
    InputEventGroup,
    InputEventGroupFolder,
    OutputGroup,
    OutputGroupFolder,
    BasicUserFolder,
    BasicUser,
    Role,
    RoleFolder,
    StorageFolder,
    Storage,
    LayoutFolder,
    LayoutGroup,
    LayoutGroupFolder,
    VideoWall,
    VideoWallFolder,
    Monitor,
    MonitorFolder,
    VideoWallPreset,
    VideoWallPresetFolder,
    MonitorPresetFolder,
    UserDefinedEventFolder,
    UserDefinedEvent,
    AnalyticsEventFolder,
    AnalyticsEvent,
    GenericEventFolder,
    GenericEventDataSourceFolder,
    GisMapLocation,
    GisMapLocationFolder,
    TimeProfile,
    TimeProfileFolder,
    MIPKind,
    MIPKindFolder,
    MIPItem,
    MIPItemFolder,
    AlarmDefinition,
    AlarmDefinitionFolder,
    LprMatchList,
    LprMatchListFolder,
    SaveSearches,
    FindSaveSearches,
    SaveSearchesFolder,
    Rule,
    RuleFolder,
    AccessControlSystem,
    AccessControlSystemFolder,
    AccessControlUnit,
    AccessControlUnitFolder,
    Site,
    SiteFolder,
    LicenseInformationFolder,
    LicenseInstalledProductFolder,
    LicenseOverviewAllFolder,
    LicenseDetailFolder,
    LicenseInformation,
    LicenseInstalledProduct,
    LicenseOverviewAll,
    LicenseDetail,
    BasicOwnerInformationFolder,
    BasicOwnerInformation;

    public String getPath() {
        return getRootPath() + this.name();
    }

    public static String getRootPath() {
        return "/";
    }
}
