version: '3.3'

networks:
  default:
    name: isc-network

services:
  isc-kibana:
    image: "${isc_docker_repo}/${container_name}:${container_version}"
    container_name: "${container_name}"
    environment:
      - SERVER_BASEPATH=/kibana
      - ELASTICSEARCH_HOSTS=http://${ES_HOST}:${ES_PORT}
    ports:
      - 5601:5601
