
package com.mip.registry;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2021-11-02T20:24:57.917-07:00
 * Generated source version: 3.3.6
 *
 */
public final class IServiceRegistrationService_WSHttpBindingIServiceRegistrationService_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "ServiceRegistrationService");

    private IServiceRegistrationService_WSHttpBindingIServiceRegistrationService_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ServiceRegistrationService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ServiceRegistrationService ss = new ServiceRegistrationService(wsdlURL, SERVICE_NAME);
        IServiceRegistrationService port = ss.getWSHttpBindingIServiceRegistrationService();

        {
        System.out.println("Invoking setServiceData...");
        java.lang.String _setServiceData_instance = "";
        java.lang.String _setServiceData_customData = "";
        java.lang.Boolean _setServiceData__return = port.setServiceData(_setServiceData_instance, _setServiceData_customData);
        System.out.println("setServiceData.result=" + _setServiceData__return);


        }
        {
        System.out.println("Invoking registerService...");
        java.lang.String _registerService_type = "";
        java.lang.String _registerService_instance = "";
        com.mip.registry.ArrayOfstring _registerService_uri = null;
        java.lang.String _registerService_name = "";
        java.lang.String _registerService_description = "";
        java.lang.String _registerService_customData = "";
        java.lang.Boolean _registerService__return = port.registerService(_registerService_type, _registerService_instance, _registerService_uri, _registerService_name, _registerService_description, _registerService_customData);
        System.out.println("registerService.result=" + _registerService__return);


        }
        {
        System.out.println("Invoking getServices...");
        com.mip.registry.ArrayOfServiceInfo _getServices__return = port.getServices();
        System.out.println("getServices.result=" + _getServices__return);


        }
        {
        System.out.println("Invoking unregisterService...");
        java.lang.String _unregisterService_instance = "";
        port.unregisterService(_unregisterService_instance);


        }
        {
        System.out.println("Invoking getServiceData...");
        java.lang.String _getServiceData_instance = "";
        java.lang.String _getServiceData__return = port.getServiceData(_getServiceData_instance);
        System.out.println("getServiceData.result=" + _getServiceData__return);


        }
        {
        System.out.println("Invoking enableService...");
        java.lang.String _enableService_instance = "";
        java.lang.Boolean _enableService_enabled = null;
        port.enableService(_enableService_instance, _enableService_enabled);


        }
        {
        System.out.println("Invoking registerServiceWithEndpoints...");
        java.lang.String _registerServiceWithEndpoints_type = "";
        java.lang.String _registerServiceWithEndpoints_instance = "";
        com.mip.registry.ArrayOfstring _registerServiceWithEndpoints_uri = null;
        java.lang.String _registerServiceWithEndpoints_name = "";
        java.lang.String _registerServiceWithEndpoints_description = "";
        java.lang.String _registerServiceWithEndpoints_customData = "";
        java.lang.String _registerServiceWithEndpoints_endpointDefinition = "";
        java.lang.Boolean _registerServiceWithEndpoints__return = port.registerServiceWithEndpoints(_registerServiceWithEndpoints_type, _registerServiceWithEndpoints_instance, _registerServiceWithEndpoints_uri, _registerServiceWithEndpoints_name, _registerServiceWithEndpoints_description, _registerServiceWithEndpoints_customData, _registerServiceWithEndpoints_endpointDefinition);
        System.out.println("registerServiceWithEndpoints.result=" + _registerServiceWithEndpoints__return);


        }
        {
        System.out.println("Invoking getServicesIncludingDisabled...");
        com.mip.registry.ArrayOfServiceInfo _getServicesIncludingDisabled__return = port.getServicesIncludingDisabled();
        System.out.println("getServicesIncludingDisabled.result=" + _getServicesIncludingDisabled__return);


        }

        System.exit(0);
    }

}
