package com.mip.registry;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2021-11-02T20:24:57.945-07:00
 * Generated source version: 3.3.6
 *
 */
@WebService(targetNamespace = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01", name = "IServiceRegistrationService")
@XmlSeeAlso({ObjectFactory.class})
public interface IServiceRegistrationService {

    @WebMethod(operationName = "SetServiceData", action = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01/IServiceRegistrationService/SetServiceData")
    @Action(input = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01/IServiceRegistrationService/SetServiceData", output = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01/IServiceRegistrationService/SetServiceDataResponse")
    @RequestWrapper(localName = "SetServiceData", targetNamespace = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01", className = "com.mip.registry.SetServiceData")
    @ResponseWrapper(localName = "SetServiceDataResponse", targetNamespace = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01", className = "com.mip.registry.SetServiceDataResponse")
    @WebResult(name = "SetServiceDataResult", targetNamespace = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01")
    public java.lang.Boolean setServiceData(

        @WebParam(name = "instance", targetNamespace = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01")
        java.lang.String instance,
        @WebParam(name = "customData", targetNamespace = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01")
        java.lang.String customData
    );

    @WebMethod(operationName = "RegisterService", action = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01/IServiceRegistrationService/RegisterService")
    @Action(input = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01/IServiceRegistrationService/RegisterService", output = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01/IServiceRegistrationService/RegisterServiceResponse")
    @RequestWrapper(localName = "RegisterService", targetNamespace = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01", className = "com.mip.registry.RegisterService")
    @ResponseWrapper(localName = "RegisterServiceResponse", targetNamespace = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01", className = "com.mip.registry.RegisterServiceResponse")
    @WebResult(name = "RegisterServiceResult", targetNamespace = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01")
    public java.lang.Boolean registerService(

        @WebParam(name = "type", targetNamespace = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01")
        java.lang.String type,
        @WebParam(name = "instance", targetNamespace = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01")
        java.lang.String instance,
        @WebParam(name = "uri", targetNamespace = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01")
        com.mip.registry.ArrayOfstring uri,
        @WebParam(name = "name", targetNamespace = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01")
        java.lang.String name,
        @WebParam(name = "description", targetNamespace = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01")
        java.lang.String description,
        @WebParam(name = "customData", targetNamespace = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01")
        java.lang.String customData
    );

    @WebMethod(operationName = "GetServices", action = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01/IServiceRegistrationService/GetServices")
    @Action(input = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01/IServiceRegistrationService/GetServices", output = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01/IServiceRegistrationService/GetServicesResponse")
    @RequestWrapper(localName = "GetServices", targetNamespace = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01", className = "com.mip.registry.GetServices")
    @ResponseWrapper(localName = "GetServicesResponse", targetNamespace = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01", className = "com.mip.registry.GetServicesResponse")
    @WebResult(name = "GetServicesResult", targetNamespace = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01")
    public com.mip.registry.ArrayOfServiceInfo getServices()
;

    @WebMethod(operationName = "UnregisterService", action = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01/IServiceRegistrationService/UnregisterService")
    @Action(input = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01/IServiceRegistrationService/UnregisterService", output = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01/IServiceRegistrationService/UnregisterServiceResponse")
    @RequestWrapper(localName = "UnregisterService", targetNamespace = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01", className = "com.mip.registry.UnregisterService")
    @ResponseWrapper(localName = "UnregisterServiceResponse", targetNamespace = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01", className = "com.mip.registry.UnregisterServiceResponse")
    public void unregisterService(

        @WebParam(name = "instance", targetNamespace = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01")
        java.lang.String instance
    );

    @WebMethod(operationName = "GetServiceData", action = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01/IServiceRegistrationService/GetServiceData")
    @Action(input = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01/IServiceRegistrationService/GetServiceData", output = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01/IServiceRegistrationService/GetServiceDataResponse")
    @RequestWrapper(localName = "GetServiceData", targetNamespace = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01", className = "com.mip.registry.GetServiceData")
    @ResponseWrapper(localName = "GetServiceDataResponse", targetNamespace = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01", className = "com.mip.registry.GetServiceDataResponse")
    @WebResult(name = "GetServiceDataResult", targetNamespace = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01")
    public java.lang.String getServiceData(

        @WebParam(name = "instance", targetNamespace = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01")
        java.lang.String instance
    );

    @WebMethod(operationName = "EnableService", action = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01/IServiceRegistrationService/EnableService")
    @Action(input = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01/IServiceRegistrationService/EnableService", output = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01/IServiceRegistrationService/EnableServiceResponse")
    @RequestWrapper(localName = "EnableService", targetNamespace = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01", className = "com.mip.registry.EnableService")
    @ResponseWrapper(localName = "EnableServiceResponse", targetNamespace = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01", className = "com.mip.registry.EnableServiceResponse")
    public void enableService(

        @WebParam(name = "instance", targetNamespace = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01")
        java.lang.String instance,
        @WebParam(name = "enabled", targetNamespace = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01")
        java.lang.Boolean enabled
    );

    @WebMethod(operationName = "RegisterServiceWithEndpoints", action = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01/IServiceRegistrationService/RegisterServiceWithEndpoints")
    @Action(input = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01/IServiceRegistrationService/RegisterServiceWithEndpoints", output = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01/IServiceRegistrationService/RegisterServiceWithEndpointsResponse")
    @RequestWrapper(localName = "RegisterServiceWithEndpoints", targetNamespace = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01", className = "com.mip.registry.RegisterServiceWithEndpoints")
    @ResponseWrapper(localName = "RegisterServiceWithEndpointsResponse", targetNamespace = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01", className = "com.mip.registry.RegisterServiceWithEndpointsResponse")
    @WebResult(name = "RegisterServiceWithEndpointsResult", targetNamespace = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01")
    public java.lang.Boolean registerServiceWithEndpoints(

        @WebParam(name = "type", targetNamespace = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01")
        java.lang.String type,
        @WebParam(name = "instance", targetNamespace = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01")
        java.lang.String instance,
        @WebParam(name = "uri", targetNamespace = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01")
        com.mip.registry.ArrayOfstring uri,
        @WebParam(name = "name", targetNamespace = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01")
        java.lang.String name,
        @WebParam(name = "description", targetNamespace = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01")
        java.lang.String description,
        @WebParam(name = "customData", targetNamespace = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01")
        java.lang.String customData,
        @WebParam(name = "endpointDefinition", targetNamespace = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01")
        java.lang.String endpointDefinition
    );

    @WebMethod(operationName = "GetServicesIncludingDisabled", action = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01/IServiceRegistrationService/GetServicesIncludingDisabled")
    @Action(input = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01/IServiceRegistrationService/GetServicesIncludingDisabled", output = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01/IServiceRegistrationService/GetServicesIncludingDisabledResponse")
    @RequestWrapper(localName = "GetServicesIncludingDisabled", targetNamespace = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01", className = "com.mip.registry.GetServicesIncludingDisabled")
    @ResponseWrapper(localName = "GetServicesIncludingDisabledResponse", targetNamespace = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01", className = "com.mip.registry.GetServicesIncludingDisabledResponse")
    @WebResult(name = "GetServicesIncludingDisabledResult", targetNamespace = "http://schemas.videoos/ServiceRegistrationService/2008/06/Vmo/01")
    public com.mip.registry.ArrayOfServiceInfo getServicesIncludingDisabled()
;
}
