version: '3.3'

networks:
  default:
    name: isc-network

services:
  isc-rabbitmq:
    image: "${isc_docker_repo}/${container_name}:${container_version}"
    container_name: "${container_name}"
    volumes:
      - type: bind
        source: "${ISC_DATA_HOME}/${container_name}"
        target: /var/lib/rabbitmq
      - type: bind
        source: "${ISC_LOGS_HOME}/${container_name}"
        target: /var/log/rabbitmq
    environment:
      - RABBITMQ_DATA=${ISC_DATA_HOME}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - 15672:15672
      - 5672:5672
