version: '3.3'

networks:
  default:
    name: isc-network

services:
  isc-postgres:
    image: "${isc_docker_repo}/${container_name}:${container_version}"
    container_name: "${container_name}"
    volumes:
      - type: bind
        source: "${ISC_DATA_HOME}/${container_name}"
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
