package com.mip.recorderCommand;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2021-11-02T20:25:04.633-07:00
 * Generated source version: 3.3.6
 *
 */
@WebService(targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", name = "RecorderCommandServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface RecorderCommandServiceSoap {

    @WebMethod(operationName = "PresetSet", action = "http://video.net/2/XProtectCSRecorderCommand/PresetSet")
    @RequestWrapper(localName = "PresetSet", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.PresetSet")
    @ResponseWrapper(localName = "PresetSetResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.PresetSetResponse")
    public void presetSet(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "presetName", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String presetName
    );

    @WebMethod(operationName = "PTZMoveAbsolute", action = "http://video.net/2/XProtectCSRecorderCommand/PTZMoveAbsolute")
    @RequestWrapper(localName = "PTZMoveAbsolute", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.PTZMoveAbsolute")
    @ResponseWrapper(localName = "PTZMoveAbsoluteResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.PTZMoveAbsoluteResponse")
    public void ptzMoveAbsolute(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "ptzArgs", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        com.mip.recorderCommand.PTZArgs ptzArgs
    );

    @WebMethod(operationName = "IsManualRecording", action = "http://video.net/2/XProtectCSRecorderCommand/IsManualRecording")
    @RequestWrapper(localName = "IsManualRecording", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.IsManualRecording")
    @ResponseWrapper(localName = "IsManualRecordingResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.IsManualRecordingResponse")
    @WebResult(name = "IsManualRecordingResult", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
    public com.mip.recorderCommand.ArrayOfManualRecordingInfo isManualRecording(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceIds", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        com.mip.recorderCommand.ArrayOfGuid deviceIds
    );

    @WebMethod(operationName = "PTZReleaseSession", action = "http://video.net/2/XProtectCSRecorderCommand/PTZReleaseSession")
    @RequestWrapper(localName = "PTZReleaseSession", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.PTZReleaseSession")
    @ResponseWrapper(localName = "PTZReleaseSessionResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.PTZReleaseSessionResponse")
    public void ptzReleaseSession(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId
    );

    @WebMethod(operationName = "OutputTrigger", action = "http://video.net/2/XProtectCSRecorderCommand/OutputTrigger")
    @RequestWrapper(localName = "OutputTrigger", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.OutputTrigger")
    @ResponseWrapper(localName = "OutputTriggerResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.OutputTriggerResponse")
    public void outputTrigger(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "duration", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        com.mip.recorderCommand.TimeDuration duration
    );

    @WebMethod(operationName = "OutputGetState", action = "http://video.net/2/XProtectCSRecorderCommand/OutputGetState")
    @RequestWrapper(localName = "OutputGetState", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.OutputGetState")
    @ResponseWrapper(localName = "OutputGetStateResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.OutputGetStateResponse")
    @WebResult(name = "OutputGetStateResult", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
    public com.mip.recorderCommand.IOState outputGetState(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId
    );

    @WebMethod(operationName = "PTZMoveStop", action = "http://video.net/2/XProtectCSRecorderCommand/PTZMoveStop")
    @RequestWrapper(localName = "PTZMoveStop", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.PTZMoveStop")
    @ResponseWrapper(localName = "PTZMoveStopResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.PTZMoveStopResponse")
    public void ptzMoveStop(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId
    );

    @WebMethod(operationName = "SmartSearchGetResult", action = "http://video.net/2/XProtectCSRecorderCommand/SmartSearchGetResult")
    @RequestWrapper(localName = "SmartSearchGetResult", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.SmartSearchGetResult")
    @ResponseWrapper(localName = "SmartSearchGetResultResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.SmartSearchGetResultResponse")
    @WebResult(name = "SmartSearchGetResultResult", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
    public com.mip.recorderCommand.SmartSearchResult smartSearchGetResult(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "smartSearchId", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String smartSearchId,
        @WebParam(name = "continueSearch", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        boolean continueSearch
    );

    @WebMethod(operationName = "MulticastContinue", action = "http://video.net/2/XProtectCSRecorderCommand/MulticastContinue")
    @RequestWrapper(localName = "MulticastContinue", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.MulticastContinue")
    @ResponseWrapper(localName = "MulticastContinueResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.MulticastContinueResponse")
    public void multicastContinue(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "multicastSessionIds", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        com.mip.recorderCommand.ArrayOfGuid multicastSessionIds
    );

    @WebMethod(operationName = "StartRecording", action = "http://video.net/2/XProtectCSRecorderCommand/StartRecording")
    @RequestWrapper(localName = "StartRecording", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.StartRecording")
    @ResponseWrapper(localName = "StartRecordingResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.StartRecordingResponse")
    @WebResult(name = "StartRecordingResult", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
    public boolean startRecording(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "recordingTimeMicroSeconds", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        long recordingTimeMicroSeconds
    );

    @WebMethod(operationName = "OutputActivate", action = "http://video.net/2/XProtectCSRecorderCommand/OutputActivate")
    @RequestWrapper(localName = "OutputActivate", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.OutputActivate")
    @ResponseWrapper(localName = "OutputActivateResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.OutputActivateResponse")
    public void outputActivate(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId
    );

    @WebMethod(operationName = "JPEGGetAtOrBefore", action = "http://video.net/2/XProtectCSRecorderCommand/JPEGGetAtOrBefore")
    @RequestWrapper(localName = "JPEGGetAtOrBefore", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.JPEGGetAtOrBefore")
    @ResponseWrapper(localName = "JPEGGetAtOrBeforeResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.JPEGGetAtOrBeforeResponse")
    @WebResult(name = "JPEGGetAtOrBeforeResult", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
    public com.mip.recorderCommand.JPEGData jpegGetAtOrBefore(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "time", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        javax.xml.datatype.XMLGregorianCalendar time
    );

    @WebMethod(operationName = "StartManualRecording", action = "http://video.net/2/XProtectCSRecorderCommand/StartManualRecording")
    @RequestWrapper(localName = "StartManualRecording", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.StartManualRecording")
    @ResponseWrapper(localName = "StartManualRecordingResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.StartManualRecordingResponse")
    @WebResult(name = "StartManualRecordingResult", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
    public com.mip.recorderCommand.ArrayOfManualRecordingResult startManualRecording(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceIds", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        com.mip.recorderCommand.ArrayOfGuid deviceIds
    );

    @WebMethod(operationName = "StopManualRecording", action = "http://video.net/2/XProtectCSRecorderCommand/StopManualRecording")
    @RequestWrapper(localName = "StopManualRecording", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.StopManualRecording")
    @ResponseWrapper(localName = "StopManualRecordingResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.StopManualRecordingResponse")
    @WebResult(name = "StopManualRecordingResult", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
    public com.mip.recorderCommand.ArrayOfManualRecordingResult stopManualRecording(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceIds", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        com.mip.recorderCommand.ArrayOfGuid deviceIds
    );

    @WebMethod(operationName = "PTZGetSessionInfo", action = "http://video.net/2/XProtectCSRecorderCommand/PTZGetSessionInfo")
    @RequestWrapper(localName = "PTZGetSessionInfo", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.PTZGetSessionInfo")
    @ResponseWrapper(localName = "PTZGetSessionInfoResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.PTZGetSessionInfoResponse")
    @WebResult(name = "PTZGetSessionInfoResult", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
    public com.mip.recorderCommand.PtzSessionInfo ptzGetSessionInfo(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId
    );

    @WebMethod(operationName = "InputGetState", action = "http://video.net/2/XProtectCSRecorderCommand/InputGetState")
    @RequestWrapper(localName = "InputGetState", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.InputGetState")
    @ResponseWrapper(localName = "InputGetStateResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.InputGetStateResponse")
    @WebResult(name = "InputGetStateResult", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
    public com.mip.recorderCommand.IOState inputGetState(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId
    );

    @WebMethod(operationName = "GetRetentionTimeLimit", action = "http://video.net/2/XProtectCSRecorderCommand/GetRetentionTimeLimit")
    @RequestWrapper(localName = "GetRetentionTimeLimit", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.GetRetentionTimeLimit")
    @ResponseWrapper(localName = "GetRetentionTimeLimitResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.GetRetentionTimeLimitResponse")
    @WebResult(name = "GetRetentionTimeLimitResult", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
    public javax.xml.datatype.XMLGregorianCalendar getRetentionTimeLimit(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId
    );

    @WebMethod(operationName = "JPEGGetLive", action = "http://video.net/2/XProtectCSRecorderCommand/JPEGGetLive")
    @RequestWrapper(localName = "JPEGGetLive", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.JPEGGetLive")
    @ResponseWrapper(localName = "JPEGGetLiveResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.JPEGGetLiveResponse")
    @WebResult(name = "JPEGGetLiveResult", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
    public com.mip.recorderCommand.JPEGData jpegGetLive(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "maxWidth", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        int maxWidth,
        @WebParam(name = "maxHeight", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        int maxHeight
    );

    @WebMethod(operationName = "SequencesGet", action = "http://video.net/2/XProtectCSRecorderCommand/SequencesGet")
    @RequestWrapper(localName = "SequencesGet", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.SequencesGet")
    @ResponseWrapper(localName = "SequencesGetResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.SequencesGetResponse")
    @WebResult(name = "SequencesGetResult", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
    public com.mip.recorderCommand.ArrayOfSequenceEntry sequencesGet(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "sequenceType", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String sequenceType,
        @WebParam(name = "minTime", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        javax.xml.datatype.XMLGregorianCalendar minTime,
        @WebParam(name = "maxTime", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        javax.xml.datatype.XMLGregorianCalendar maxTime,
        @WebParam(name = "maxCount", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        int maxCount
    );

    @WebMethod(operationName = "JPEGGetAtOrAfter", action = "http://video.net/2/XProtectCSRecorderCommand/JPEGGetAtOrAfter")
    @RequestWrapper(localName = "JPEGGetAtOrAfter", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.JPEGGetAtOrAfter")
    @ResponseWrapper(localName = "JPEGGetAtOrAfterResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.JPEGGetAtOrAfterResponse")
    @WebResult(name = "JPEGGetAtOrAfterResult", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
    public com.mip.recorderCommand.JPEGData jpegGetAtOrAfter(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "time", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        javax.xml.datatype.XMLGregorianCalendar time
    );

    @WebMethod(operationName = "PresetMoveTo", action = "http://video.net/2/XProtectCSRecorderCommand/PresetMoveTo")
    @RequestWrapper(localName = "PresetMoveTo", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.PresetMoveTo")
    @ResponseWrapper(localName = "PresetMoveToResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.PresetMoveToResponse")
    public void presetMoveTo(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "presetName", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String presetName
    );

    @WebMethod(operationName = "SendDriverCommandWithResponse", action = "http://video.net/2/XProtectCSRecorderCommand/SendDriverCommandWithResponse")
    @RequestWrapper(localName = "SendDriverCommandWithResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.SendDriverCommandWithResponse")
    @ResponseWrapper(localName = "SendDriverCommandWithResponseResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.SendDriverCommandWithResponseResponse")
    @WebResult(name = "SendDriverCommandWithResponseResult", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
    public java.lang.String sendDriverCommandWithResponse(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "command", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String command,
        @WebParam(name = "parameter", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String parameter
    );

    @WebMethod(operationName = "MulticastStop", action = "http://video.net/2/XProtectCSRecorderCommand/MulticastStop")
    @RequestWrapper(localName = "MulticastStop", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.MulticastStop")
    @ResponseWrapper(localName = "MulticastStopResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.MulticastStopResponse")
    public void multicastStop(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "multicastSessionIds", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        com.mip.recorderCommand.ArrayOfGuid multicastSessionIds
    );

    @WebMethod(operationName = "PTZMoveHome", action = "http://video.net/2/XProtectCSRecorderCommand/PTZMoveHome")
    @RequestWrapper(localName = "PTZMoveHome", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.PTZMoveHome")
    @ResponseWrapper(localName = "PTZMoveHomeResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.PTZMoveHomeResponse")
    public void ptzMoveHome(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId
    );

    @WebMethod(operationName = "SmartSearchGetStatus", action = "http://video.net/2/XProtectCSRecorderCommand/SmartSearchGetStatus")
    @RequestWrapper(localName = "SmartSearchGetStatus", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.SmartSearchGetStatus")
    @ResponseWrapper(localName = "SmartSearchGetStatusResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.SmartSearchGetStatusResponse")
    @WebResult(name = "SmartSearchGetStatusResult", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
    public com.mip.recorderCommand.SmartSearchStatus smartSearchGetStatus(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "smartSearchId", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String smartSearchId
    );

    @WebMethod(operationName = "PTZMoveStart", action = "http://video.net/2/XProtectCSRecorderCommand/PTZMoveStart")
    @RequestWrapper(localName = "PTZMoveStart", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.PTZMoveStart")
    @ResponseWrapper(localName = "PTZMoveStartResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.PTZMoveStartResponse")
    public void ptzMoveStart(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "ptzArgs", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        com.mip.recorderCommand.PTZArgs ptzArgs
    );

    @WebMethod(operationName = "PTZCenter", action = "http://video.net/2/XProtectCSRecorderCommand/PTZCenter")
    @RequestWrapper(localName = "PTZCenter", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.PTZCenter")
    @ResponseWrapper(localName = "PTZCenterResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.PTZCenterResponse")
    public void ptzCenter(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "refWidth", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        double refWidth,
        @WebParam(name = "refHeight", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        double refHeight,
        @WebParam(name = "centerX", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        double centerX,
        @WebParam(name = "centerY", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        double centerY,
        @WebParam(name = "zoom", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        double zoom
    );

    @WebMethod(operationName = "TimeLineInformationGet", action = "http://video.net/2/XProtectCSRecorderCommand/TimeLineInformationGet")
    @RequestWrapper(localName = "TimeLineInformationGet", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.TimeLineInformationGet")
    @ResponseWrapper(localName = "TimeLineInformationGetResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.TimeLineInformationGetResponse")
    @WebResult(name = "TimeLineInformationGetResult", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
    public com.mip.recorderCommand.ArrayOfTimeLineInformationData timeLineInformationGet(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "timeLineInformationTypes", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        com.mip.recorderCommand.ArrayOfGuid timeLineInformationTypes,
        @WebParam(name = "timeLineInformationBeginTime", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        javax.xml.datatype.XMLGregorianCalendar timeLineInformationBeginTime,
        @WebParam(name = "timeLineInformationInterval", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        com.mip.recorderCommand.TimeDuration timeLineInformationInterval,
        @WebParam(name = "timeLineInformationCount", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        int timeLineInformationCount
    );

    @WebMethod(operationName = "SmartSearchStart", action = "http://video.net/2/XProtectCSRecorderCommand/SmartSearchStart")
    @RequestWrapper(localName = "SmartSearchStart", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.SmartSearchStart")
    @ResponseWrapper(localName = "SmartSearchStartResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.SmartSearchStartResponse")
    @WebResult(name = "SmartSearchStartResult", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
    public java.lang.String smartSearchStart(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "searchBeginTime", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        javax.xml.datatype.XMLGregorianCalendar searchBeginTime,
        @WebParam(name = "searchEndTime", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        javax.xml.datatype.XMLGregorianCalendar searchEndTime,
        @WebParam(name = "sensitivity", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        int sensitivity,
        @WebParam(name = "searchInterval", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        com.mip.recorderCommand.TimeDuration searchInterval,
        @WebParam(name = "searchMask", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        com.mip.recorderCommand.ImageMask searchMask,
        @WebParam(name = "ignoreInitialMotion", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        boolean ignoreInitialMotion,
        @WebParam(name = "resultMotionMaskSize", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        com.mip.recorderCommand.Size resultMotionMaskSize
    );

    @WebMethod(operationName = "SendDriverCommand", action = "http://video.net/2/XProtectCSRecorderCommand/SendDriverCommand")
    @RequestWrapper(localName = "SendDriverCommand", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.SendDriverCommand")
    @ResponseWrapper(localName = "SendDriverCommandResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.SendDriverCommandResponse")
    public void sendDriverCommand(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "command", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String command
    );

    @WebMethod(operationName = "OutputDeactivate", action = "http://video.net/2/XProtectCSRecorderCommand/OutputDeactivate")
    @RequestWrapper(localName = "OutputDeactivate", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.OutputDeactivate")
    @ResponseWrapper(localName = "OutputDeactivateResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.OutputDeactivateResponse")
    public void outputDeactivate(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId
    );

    @WebMethod(operationName = "PTZReserveSession", action = "http://video.net/2/XProtectCSRecorderCommand/PTZReserveSession")
    @RequestWrapper(localName = "PTZReserveSession", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.PTZReserveSession")
    @ResponseWrapper(localName = "PTZReserveSessionResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.PTZReserveSessionResponse")
    public void ptzReserveSession(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId
    );

    @WebMethod(operationName = "SequencesGetAround", action = "http://video.net/2/XProtectCSRecorderCommand/SequencesGetAround")
    @RequestWrapper(localName = "SequencesGetAround", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.SequencesGetAround")
    @ResponseWrapper(localName = "SequencesGetAroundResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.SequencesGetAroundResponse")
    @WebResult(name = "SequencesGetAroundResult", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
    public com.mip.recorderCommand.ArrayOfSequenceEntry sequencesGetAround(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "sequenceType", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String sequenceType,
        @WebParam(name = "centerTime", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        javax.xml.datatype.XMLGregorianCalendar centerTime,
        @WebParam(name = "maxCountBefore", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        int maxCountBefore,
        @WebParam(name = "maxCountAfter", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        int maxCountAfter
    );

    @WebMethod(operationName = "SequencesGetAroundWithSpan", action = "http://video.net/2/XProtectCSRecorderCommand/SequencesGetAroundWithSpan")
    @RequestWrapper(localName = "SequencesGetAroundWithSpan", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.SequencesGetAroundWithSpan")
    @ResponseWrapper(localName = "SequencesGetAroundWithSpanResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.SequencesGetAroundWithSpanResponse")
    @WebResult(name = "SequencesGetAroundWithSpanResult", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
    public com.mip.recorderCommand.ArrayOfSequenceEntry sequencesGetAroundWithSpan(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "sequenceType", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String sequenceType,
        @WebParam(name = "centerTime", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        javax.xml.datatype.XMLGregorianCalendar centerTime,
        @WebParam(name = "maxTimeBefore", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        com.mip.recorderCommand.TimeDuration maxTimeBefore,
        @WebParam(name = "maxCountBefore", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        int maxCountBefore,
        @WebParam(name = "maxTimeAfter", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        com.mip.recorderCommand.TimeDuration maxTimeAfter,
        @WebParam(name = "maxCountAfter", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        int maxCountAfter
    );

    @WebMethod(operationName = "PTZExtendedManualSession", action = "http://video.net/2/XProtectCSRecorderCommand/PTZExtendedManualSession")
    @RequestWrapper(localName = "PTZExtendedManualSession", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.PTZExtendedManualSession")
    @ResponseWrapper(localName = "PTZExtendedManualSessionResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.PTZExtendedManualSessionResponse")
    public void ptzExtendedManualSession(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId
    );

    @WebMethod(operationName = "PTZGetAbsolutePosition", action = "http://video.net/2/XProtectCSRecorderCommand/PTZGetAbsolutePosition")
    @RequestWrapper(localName = "PTZGetAbsolutePosition", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.PTZGetAbsolutePosition")
    @ResponseWrapper(localName = "PTZGetAbsolutePositionResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.PTZGetAbsolutePositionResponse")
    @WebResult(name = "PTZGetAbsolutePositionResult", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
    public com.mip.recorderCommand.PTZArgs ptzGetAbsolutePosition(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId
    );

    @WebMethod(operationName = "PTZDeactivatePatrollingSchema", action = "http://video.net/2/XProtectCSRecorderCommand/PTZDeactivatePatrollingSchema")
    @RequestWrapper(localName = "PTZDeactivatePatrollingSchema", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.PTZDeactivatePatrollingSchema")
    @ResponseWrapper(localName = "PTZDeactivatePatrollingSchemaResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.PTZDeactivatePatrollingSchemaResponse")
    public void ptzDeactivatePatrollingSchema(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "patrollingSchemaId", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String patrollingSchemaId
    );

    @WebMethod(operationName = "SequencesGetTypes", action = "http://video.net/2/XProtectCSRecorderCommand/SequencesGetTypes")
    @RequestWrapper(localName = "SequencesGetTypes", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.SequencesGetTypes")
    @ResponseWrapper(localName = "SequencesGetTypesResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.SequencesGetTypesResponse")
    @WebResult(name = "SequencesGetTypesResult", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
    public com.mip.recorderCommand.ArrayOfSequenceType sequencesGetTypes(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId
    );

    @WebMethod(operationName = "MulticastStart", action = "http://video.net/2/XProtectCSRecorderCommand/MulticastStart")
    @RequestWrapper(localName = "MulticastStart", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.MulticastStart")
    @ResponseWrapper(localName = "MulticastStartResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.MulticastStartResponse")
    @WebResult(name = "MulticastStartResult", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
    public com.mip.recorderCommand.ArrayOfMulticastInfo multicastStart(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceIds", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        com.mip.recorderCommand.ArrayOfGuid deviceIds,
        @WebParam(name = "clientCapabilities", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        com.mip.recorderCommand.ClientCapabilities clientCapabilities
    );

    @WebMethod(operationName = "GetVersion", action = "http://video.net/2/XProtectCSRecorderCommand/GetVersion")
    @RequestWrapper(localName = "GetVersion", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.GetVersion")
    @ResponseWrapper(localName = "GetVersionResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.GetVersionResponse")
    @WebResult(name = "GetVersionResult", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
    public int getVersion()
;

    @WebMethod(operationName = "JPEGGetAt", action = "http://video.net/2/XProtectCSRecorderCommand/JPEGGetAt")
    @RequestWrapper(localName = "JPEGGetAt", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.JPEGGetAt")
    @ResponseWrapper(localName = "JPEGGetAtResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.JPEGGetAtResponse")
    @WebResult(name = "JPEGGetAtResult", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
    public com.mip.recorderCommand.JPEGData jpegGetAt(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "time", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        javax.xml.datatype.XMLGregorianCalendar time
    );

    @WebMethod(operationName = "PTZActivatePatrollingSchema", action = "http://video.net/2/XProtectCSRecorderCommand/PTZActivatePatrollingSchema")
    @RequestWrapper(localName = "PTZActivatePatrollingSchema", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.PTZActivatePatrollingSchema")
    @ResponseWrapper(localName = "PTZActivatePatrollingSchemaResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.PTZActivatePatrollingSchemaResponse")
    public void ptzActivatePatrollingSchema(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "patrollingSchemaId", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String patrollingSchemaId
    );

    @WebMethod(operationName = "PTZMoveRelative", action = "http://video.net/2/XProtectCSRecorderCommand/PTZMoveRelative")
    @RequestWrapper(localName = "PTZMoveRelative", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.PTZMoveRelative")
    @ResponseWrapper(localName = "PTZMoveRelativeResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.PTZMoveRelativeResponse")
    public void ptzMoveRelative(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "ptzArgs", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        com.mip.recorderCommand.PTZArgs ptzArgs
    );

    @WebMethod(operationName = "SmartSearchCancel", action = "http://video.net/2/XProtectCSRecorderCommand/SmartSearchCancel")
    @RequestWrapper(localName = "SmartSearchCancel", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.SmartSearchCancel")
    @ResponseWrapper(localName = "SmartSearchCancelResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.SmartSearchCancelResponse")
    public void smartSearchCancel(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "smartSearchId", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String smartSearchId
    );

    @WebMethod(operationName = "PTZRectangle", action = "http://video.net/2/XProtectCSRecorderCommand/PTZRectangle")
    @RequestWrapper(localName = "PTZRectangle", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.PTZRectangle")
    @ResponseWrapper(localName = "PTZRectangleResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.PTZRectangleResponse")
    public void ptzRectangle(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "refWidth", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        double refWidth,
        @WebParam(name = "refHeight", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        double refHeight,
        @WebParam(name = "left", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        double left,
        @WebParam(name = "top", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        double top,
        @WebParam(name = "bottom", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        double bottom,
        @WebParam(name = "right", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        double right
    );

    @WebMethod(operationName = "PresetGetList", action = "http://video.net/2/XProtectCSRecorderCommand/PresetGetList")
    @RequestWrapper(localName = "PresetGetList", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.PresetGetList")
    @ResponseWrapper(localName = "PresetGetListResponse", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand", className = "com.mip.recorderCommand.PresetGetListResponse")
    @WebResult(name = "PresetGetListResult", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
    public com.mip.recorderCommand.ArrayOfString presetGetList(

        @WebParam(name = "token", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://video.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId
    );
}
