---
ansible_python_interpreter: /usr/bin/python3
isc_monit_home: /opt/monit
isc_docker_home: /opt/docker
isc_data_home: /opt/data
isc_logs_home: /opt/logs

isc_rabbitmq_user: user
isc_rabbitmq_password: pass

# monit role
monit_home_dir: "{{ isc_monit_home }}"
monit_scripts_dir: "{{ monit_home_dir }}/scripts"
monit_log_file: "{{ isc_logs_home }}/monit.log"
monit_httpd_acl_rules:
  - 'admin:monit'
monit_mail_enabled: true
monit_mailserver_host: smtp.gmail.com
monit_mailserver_port: 587
monit_mailserver_user: notifications@usd.com
monit_mailserver_password: 'pass'
monit_mailserver_ssl_version: tls
monit_mailserver_timeout: 30
monit_alert_addresses:
  - engineering@iscweb.io

# docker role
docker_registiries:
  nexus.iscweb.io:5000:
    username: nexus_publisher
    password: pass
    insecure: true
  nexus.iscweb.io:5001:
    username: nexus_publisher
    password: pass
    insecure: true
  nexus.iscweb.io:5002:
    username: nexus_publisher
    password: pass
    insecure: true
docker_users:
  - satoshi
  - ubuntu
